### ISSUE TITLE
2016009 in some cases only zeros in all cells

### ISSUE THREAD

**Issue by rvdlaar8** [sdcTools/UserSupport#10]
Version used: 4.1.3
## Windows

After an "error" (for instance when not rounded correctly) then in some cases only zero values in all cells.
After a correct result, and then en 'error', in some cases the old solution returns.

**Comment by ppdewolf** [comment]
Cannot reproduce anymore. Is there an MWE?

**Comment by ppdewolf** [comment]
Closing because cannot reproduce the error anymore.
