### ISSUE TITLE
Inconsistency in order of categories

### ISSUE THREAD

**Issue by mancag** [sdcTools/UserSupport#100]
**SDC tool used:** cellKey  
**Version used:**  0.13.4
**Operating system used:** Windows

---

Dear all,

When protecting (perturbing) a table with R-package cellKey I found an inconsistency explained below.
I have a 3-dim table VAR1 x VAR2 x VAR3. The hierarchy for VAR1 has 3 cases, in which the lowest level in equal to the higher level (e.g. 0101047001 = 0101047), while in all other cases the sum of more than one lowest level is equal to the higher level (e.g. 0101002 = 0101002001 + 0101002002 + ... + 0101002008).
In Tau-Argus CSV for pivot table output, categories are ordered first by VAR1, then by VAR2, then by VAR3. But in R, this is not the case only if the lowest level is equal to the higher level.
In the attached file, you can see an example of correct order from Tau-Argus and incorrect order from R.

Best,
Manca Golmajer

[example.xlsx](https://github.com/sdcTools/UserSupport/files/2519506/example.xlsx)

**Comment by mancag** [comment]
Dear Bernhard,
I'm not at work this week so I can't provide you the code. But I can tell you that I defined the hierarchies using labels and levels (with @) (hope this is enough).
In comparison with Tau-Argus I wasn't precise enough. I was referring to Tau-Argus' suppression output (e.g. if a table is suppressed with Tau-Argus 3.5.0 or 4.1.6). In my opinion it would be convenient to have the same order of categories in the output, but of course this is not obligatory.
Best,
Manca

**Comment by bernhard-da** [comment]
@mancag please re-open if you have the code or still think that this is an issue
