### ISSUE TITLE
Suggestion for generation of p-table

### ISSUE THREAD

**Issue by mancag** [sdcTools/UserSupport#107]
**SDC tool used:** ptable
**Version used:**  0.1.11
**Operating system used:** Windows

---
Dear all,

I generated a p-table using ck_create_pTable, e.g.
pTab <- ck_create_pTable(D=3, V=1, type="destatis")
Using this p-table, zeros are perturbed into zeros.
In my opinion, it would be very convenient if it would be possible also to perturb positives into positives. Consequently, unpopulated areas would stay unpopulated and populated areas would stay populated.

Best,
Manca Golmajer

**Comment by ppdewolf** [comment]
Part of the protection when using noise addition with the Cell Key approach is due to the fact that positive figures can become zero with a certain probability. So this would not be a good option in my view.

@tenderle and @Sarah-Giessing

**Comment by tenderle** [comment]
As @ppdewolf pointed out, uncertainty with respect to all frequencies (also zeroes) is a key issue of the method. Another point is the unbiasedness issue. @mancag: You can find further explanations in Deliverable 4.1 of our SGA. @Sarah-Giessing gives examples in the document.
