### ISSUE TITLE
2016010 Generate Apriori

### ISSUE THREAD

**Issue by rvdlaar8** [sdcTools/UserSupport#11]
Version used: 4.1.3
Windows
---
In de Generate Apriori kan niet langer de costs als enige worden gekozen. Er _moet_ een status gekozen worden. "Omit" zorgt er voor dat de cel helemaal niet wordt weggeschreven.

Fixed

**Comment by ppdewolf** [comment]
It is now possible again to change the weight only (omit now only has impact on status)
