### ISSUE TITLE
A priori file issue

### ISSUE THREAD

**Issue by LuigiVirgili** [sdcTools/UserSupport#111]
[esempio_tau.zip](https://github.com/sdcTools/UserSupport/files/2971971/esempio_tau.zip)

*Please specify*  
**SDC tool used:**  tau-argus  
**Version used:**  TauArgus4.1.7b4
**Operating system used:** Windows 7

Dear Peter Paul,
in the a priori file the last line seems omitted. In the attachment you will find the following files:
-	”tabella_safe” (it is the safe table)
-	“tabella_safe_history_350” (it is the a priori file from “tabella _safe” generated by using the old tau-argus version: 3.5.0. built 27 ): it has 181 lines.
-	“tabella_safe_history” (it is the a priori file from “tabella _safe” generated by using the tau version 4.1.7 build 4): it seems affected by a bug because it has 180 lines only (the 181st one  - "16","8",p  -  is omitted).

Thank you
Luigi

---

**Comment by g3o2** [comment]
@ppdewolf and @LuigiVirgili , do you see any workaround that could be used to counteract the current bug?

**Comment by ppdewolf** [comment]
Will be fixed in the next release (4.2.0 build 5)
