### ISSUE TITLE
Different suppressions patterns in neuwer and older tau-Argus

### ISSUE THREAD

**Issue by r-tent** [sdcTools/UserSupport#112]
**SDC tool used:** tau-argus
**Version used:**  3.5.0, 4.1.7 and 4.1.12.Beta
**Operating system used:** Windows7

Dear Peter Paul,

while using the modular suppression method of tau-Argus an obscurity occured to me: Using the same data set in version 3.5.0 as well as 4.1.7 of tau-Argus led to different suppression patterns (as I verified later on, results in 4.1.12.Beta are identical to 4.1.7).

I tried to shrink down the size of my data set by simultaneously maintaining said irregularity.  A table of size 7x12 was the smallest I managed to produce here. Said data (tab & rda) you find attached.
When feeding the data to tau-Argus (manual safety range set to 0%) you should notice that older argus doesn't set any additional cell to unsafe, while newer argus suppresses cell A01/B10. Here it doesn't matter if you use Cplex or Xpress, the results are the same.

I hope you're able to find out where this inconsistency stems from.

Thanks a lot,
Reinhard

---
[min_example.zip](https://github.com/sdcTools/UserSupport/files/3017197/min_example.zip)

**Comment by ppdewolf** [comment]
Hi,
I noticed something like this as well after some discussion with some German colleagues. I was able to fix that bug, but I am waiting a little bit for a new release (I'll try to do so as soon as possible).

For the time being: I (pre-)released a newer version of [**tauhitas.dll**](https://github.com/sdcTools/tauhitas/releases/tag/4.2.4.1). If you replace the tauhitas.dll in your tau-argus directory by this new one, at least the bug I encountered is solved and probably yours as well. Please let me know if it works 😉

**Comment by r-tent** [comment]
Hi and thnaks for your answering so quickly :-)
I replaced the tauhitas.dll in tau-Argus 4.1.7 with the one you linked above. Unfortunately the result doesn't change... :-/

**Comment by ppdewolf** [comment]
Hmmm. Then it will take a little longer I guess 😞

**Comment by r-tent** [comment]
I'm sorry ^^'

**Comment by ppdewolf** [comment]
Am I correct that this only happens when *no* additional Modular options are selected?

**Comment by ppdewolf** [comment]
Note that `manual safety range set to 0%` does not do anything, since you specified the `upl` and `lpl` in your `.tab` file.

**Comment by ppdewolf** [comment]
Looks like you found a bug in the "old" version 😅 

You specify `lpl` and `upl` in your `.tab` file. In the "old" version the `lpl` was not correctly copied (it was rounded to an integer), whereas in the "new" version the `lpl` is exactly like specified in the `.tab` file.
In the "old" GUI the correct `lpl` is displayed, but in the table that is protected somehow a rounded `lpl` is used...(`upl` is still exact) 
In the "new" GUI a rounded `lpl` and `upl` is displayed, but the exact values are used in the table that is protected...

So essentially the "new" version is correct and the "old" version is not.

If I change the `lpl` in the table that is protected to the exact values by hand, the "old" and the "new" versions give the same results (one additional suppression).

**Comment by r-tent** [comment]
Right, that would have been a useful information: I only use "do singeltons" as option.

**Comment by r-tent** [comment]
It's interresting that neither of the versions displays the same lpl/upl as they use for calculation :-D
Thank you very much for figuring out the cause so quickly. Since it's the "old" version there won't be a bug fix I guess?

Best regards,
Reinhard

**Comment by ppdewolf** [comment]
I guess the "bug-fix" for the "old" version is: use the "new" version 😉
