### ISSUE TITLE
Error loading cellKey R package

### ISSUE THREAD

**Issue by ppdewolf** [sdcTools/UserSupport#113]
**SDC tool used:** cellKey R-package
**Version used:**  ???
**Operating system used:** Windows

---

When I use `library(cellKey)` (Rstudio 1.1.463 and R 3.5.2), I get the following error :

`Error: package or namespace load failed for ‘cellKey’:`
`object ‘add_nodes’ is not exported by 'namespace:sdcTable'`

Note, I first did `update.packages(ask = FALSE)`.

**Comment by ppdewolf** [comment]
Apparently I had 0.15.0 that I tried to load. Now I've installed 0.16.1 and now it loads correctly.

Apparently, `update.packages` led to a new version of `sdcTables`, but not to a new version of `cellKey` (because the latter is not on CRAN?).

**Comment by bernhard-da** [comment]
@ppdewolf yes, indeed this problem is due to the fact that the package was not installed from CRAN.

I can't put `cellKey` on CRAN until @tenderle puts `ptable` there because of the direct dependence.
