### ISSUE TITLE
Establish k-anonymity button still disappears in current version

### ISSUE THREAD

**Issue by santalw** [sdcTools/UserSupport#114]
SDC tool used: sdcMicro, using the UI from command sdcApp()

Version used: the latest version of shiny and sdcMicro (just updated using update.packages(ask=FALSE)) on May 1, 2019

Operating system used: Mac, with Chrome browser, GUI launched from R 3.5.1 and R studio 1.1.463

Issue:
---
The Establish K-anonymity button is available when both "setting importance" and "apply on subset key variable" are chosen as No. However, once I click yes for any of the two advance options, the button disappears. The button will reappear once I change "yes" to "no" for both options, but this is limiting the functionalities of the GUI.

There was an similar issue reported here and the issue had been closed on Jan 2018: #83 

Please advice how can I set up importance vector using the GUI. Thanks!

**Comment by bernhard-da** [comment]
@santalw thx for reporting, however, i can't reproduce.

once you specify `apply on subset key variable`, you need to enable `Apply k-anonymity to all subsets of `n` key variables?` for at least one subgroup. only in this case the button will appear.

apart from that, i think everything works as expected. could you please paste the output of the reproducibility tab (the R-code) here just before you play around in the k-anonymity tab? thx.

**Comment by santalw** [comment]
Thanks for your prompt reply!
I am able to reproduce the case you described for applying on subsets of key variable, but I still cannot get the button back when I just want to modify importance.

Here is a screenshot of the GUI once modify importance is selected as Yes, and the importance is ranked for every key variables.
![Kanonymity](https://user-images.githubusercontent.com/50127069/57085727-d12b9a00-6cca-11e9-8654-52613d3332f5.jpg)

Here is the code generated prior to this step:
`require(sdcMicro)
inputdata <- readMicrodata(path="mypath/exportedData_HHsubset.rdata", type="R", convertCharToFac=TRUE, drop_all_missings=TRUE)
inputdataB <- inputdata

## Set up sdcMicro object
sdcObj <- createSdcObj(dat=inputdata,
        keyVars=c("REGION","URBRUR","HHSIZE","RELIG","OWNAGLAND"),
        numVars=c("LANDSIZEHA","INCRMT","INCWAGE","INCFARMBSN","INCNFARMBSN","INCRENT","INCFIN","INCPENSN","INCOTHER","INCTOTGROSSHH","THOUSEXP","TFOODEXP","TALCHEXP","TCLTHEXP","TFURNEXP","THLTHEXP","TTRANSEXP","TCOMMEXP","TRECEXP","TEDUEXP","TRESTHOTEXP","TMISCEXP","TANHHEXP"),
        weightVar=c("WGTPOP"),
        hhId=c("IDH"),
        strataVar=NULL,
        pramVars=c("ROOF","TOILET","ELECTCON","FUELCOOK","WATER","OWNMOTORCYCLE","CAR","TV","LIVESTOCK"),
        excludeVars=NULL,
        seed=0,
        randomizeRecords=FALSE,
        alpha=c(1))

## Store name of uploaded file
opts <- get.sdcMicroObj(sdcObj, type="options")
opts$filename <- "exportedData_HHsubset.rdata"
sdcObj <- set.sdcMicroObj(sdcObj, type="options", input=list(opts))

`
more background: I am learning how to apply disclosure control using the GUI by following the case studies in Statistical Disclosure Control: A Practice Guide. The variables show up above are all from the dataset provided by the case studies. Currently I am at step8a where importance vector need to be set up before establishing 2-anonymity for the household level data subset. 

Thanks again!

**Comment by bernhard-da** [comment]
hi @santalw 

thx for the report. unfortunately, i can't reproduce with the testdata (could you share the `exportedData_HHsubset.rdata` file?). do you see any errors in the R console? 

can you also post the output of `devtools::sesssion_info()`

thx.

**Comment by santalw** [comment]
Thanks for your responding!
Yes, there are error messages in the console:
```
> sdcApp()
Listening on http://127.0.0.1:5312
Warning: Error in if: argument is of length zero
  97: renderUI [controllers/ui_categorical.R#439]
  96: func
  83: origRenderFunc
  82: output$kanon_btn
   2: runApp
   1: sdcApp
Warning in `<reactive:kAnon_impvec>`(...) : NAs introduced by coercion
```
The last line of warning is generated when I click on "Yes" for "do you want to modify importance of key variables for the suppression?"

Here is the output for session info:
```
> devtools::session_info()
- Session info -------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Canada.1252         
 ctype    English_Canada.1252         
 tz       America/New_York            
 date     2019-05-03       

- packages --------------- (for confidentiality reason I only copied several relevant ones. Please let me know if you would like to see the full list. Thank you!)
sdcMicro      * 5.3.0   2018-05-16 [3] CRAN (R 3.5.3)
shiny         * 1.3.2   2019-04-22 [3] CRAN (R 3.5.3)
shinyBS       * 0.61    2015-03-31 [3] CRAN (R 3.5.3)

```
Thanks!

**Comment by bernhard-da** [comment]
hi @santalw 

I think I know why I was not able to reproduce. On the computer I tested I had the latest version from github installed where this issue was already fixed. So it would be great if you could test with:

```
# install latest version from github
remotes::install_github("sdcTools/sdcMicro")

# run tests
```

and confirm that everything is working. we are in the process of uploading a new version of sdcMicro soon. if everything is ok, you can remove this devel-version using `remove.packages("sdcMicro)` again and update with `update.packages()` once the new version hits CRAN.

**Comment by santalw** [comment]
Thanks @bernhard-da ! There is no problem in the new version. Could you give us an estimated time for the next release? We forward to the new version.
Good luck to your team:)

**Comment by alexkowa** [comment]
New version on CRAN from 2019-05-16

**Comment by Freeedim** [comment]
Hi there!
I am now experiencing the very same issue with sdcMicro 5.5.1. Possible regression?

**Comment by bernhard-da** [comment]
hi  @Freeedim  thx, can you please provide the example (data) and code that you used? thx.
