### ISSUE TITLE
Running batch files from python

### ISSUE THREAD

**Issue by gosiagit** [sdcTools/UserSupport#118]
Hello, 

Would you know how to run a batch file from python?
I manage to call argus.exe but I don't know how to run afterwards the .arb file from python.

Argus_exe= '\"\"D:\\TauArgus4.1.12BETA\\TauArgus.exe\"\"' 
os.system(Argus_exe)
Argus_arb = '\"\"TauArgus "\D:\argus\_batch_test.arb"\"\"' 

Thanks!
Gosia

**SDC tool used: tau-argus
**Version used: Version 4.1.12_BETA
**Operating system used:** (Windows)

---

**Comment by alexkowa** [comment]
It is implemented in sdcTable to run batch files from R (https://github.com/sdcTools/sdcTable/blob/master/R/runArgusBatchFile.R), so maybe you can model your Python code after that. Especially line 75 builds the command to be called in the form:
Executable BatchFile DataDir

You seem to start the Exe without additional parameters.

**Comment by gosiagit** [comment]
Many thanks! I managed to make it work - code below for python's users. 

However, when running it from python I get an error: "Java heap space" - which prevents Argus from running (while the same error does NOT prevent a batch file run from Argus directly to finish).

Would you know how to solve it?

```
import subprocess
Argus_exe= r"D:\\TauArgus4.1.12BETA\\TauArgus.exe"
Argus_batch = r"\\D:\\argus test\\_batch.arb"
Argus_log = r"\\D:\\argus test\\_log.log"

cp = subprocess.run([Argus_exe, Argus_batch, Argus_log ], check=True,  stdout=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
cp.returncode
cp.stderr
```

**Comment by alexkowa** [comment]
This sounds like it the JVM Heap space maximum must be increased, again I am not sure how to do that from python.
In R it would work like:
`options(java.parameters = "-Xmx20g")`
to set the max heap space size to 20 GB

**Comment by gosiagit** [comment]
Thanks for the tip! I will try to figure it out for python. 
Is it global system setting or should I add this option when calling Argus / batch file?

**Comment by alexkowa** [comment]
There is probably also a system-wide option, in R usually I set it within a session.

**Comment by gosiagit** [comment]
Thanks! For python it seems to be:
`os.environ["JAVA_OPTS"] = "-Xmx20g"`
