### ISSUE TITLE
Java(TM) Platform SE binary has stopped working

### ISSUE THREAD

**Issue by rvdlaar8** [sdcTools/UserSupport#12]
Dear, Tau argus team,

At beginning I read micro and meta data using tau argus 4.1.2 build 1. When specified table I get error, that tau argus are closing and do not make any calculations.

In attachment I add print screen how look window before select compute table and java error.

Maybe you can explain why it happens?

![image001](https://cloud.githubusercontent.com/assets/19902165/16375760/4edae01a-3c5d-11e6-86b4-2b3fc41776ea.gif)
![image002](https://cloud.githubusercontent.com/assets/19902165/16375764/5bf0fe92-3c5d-11e6-837c-2d7460234fc4.gif)

With best wishes,

Ilona Kallione

**Comment by ppdewolf** [comment]
I’m not sure where the Java error is coming from, but the specification of the dominance rule might be the reason. You specify that the largest 80 contributors of a cell should not contribute more than 90% of the cell total… (n=80 and k=90 in your settings). That is a very unrealistic approach.

Usually the n is 1, 2 or 3 at the most. I’ll have to check the code, but I can imagine that taking n=80 was not foreseen and might lead to memory and display problems causing the Java error.

So I suggest to take the n at most 3.

Actually I think what you intend to use is two dominance rules. The first is (1,80)-dominance (largest < 80%) and the second is (2,90)-dominance (largest two < 90%). In that case you have to specify
          |   n   |   k   |
          | :---: | :---: |
 Ind-1 |   1   |  80  |
 Ind-2 |   2   |  90  |

Please have a look at the manual how to specify the dominance rule. For background information on the dominance rule I suggest the Wiley book “Statistical Disclosure Control” (2012), ISBN 978-1-119-97815-2.
