### ISSUE TITLE
provide full documentation of the batch command <READTABLE>

### ISSUE THREAD

**Issue by g3o2** [sdcTools/UserSupport#120]
**SDC tool used:** tau-argus
**Version used:**  4.1.7 (build 4)
**Operating system used:** Windows

---

The documentation for `<READTABLE>` specifies:

> Just reads the tabular inputfile; If the only parameter = 1 the “compute missing totals” procedure will be used. Default = do not compute this.

What are the parameters and parameter values of this command ?

**Comment by ppdewolf** [comment]
I admit that the manual hasn't been updated lately...

But each release is accompanied by Release Notes that includes a section "Version history". The version history shows the differences/changes between versions. From the [Release Notes of Version 4.1.7](https://github.com/sdcTools/tauargus/releases/download/v4.1.7b4/ReleaseNoteTAU4.1.7.pdf) (among the "Changes with respect to version 4.1.5"):

> The `<READTABLE>` command in the batch-file now accepts as parameter:
> - 0: (default) an additive table is required
> - 1: compute sub-totals in case non-additive
> - 2: allow non-additivity
