### ISSUE TITLE
document what has to be specified before <READTABLE>

### ISSUE THREAD

**Issue by g3o2** [sdcTools/UserSupport#121]
**SDC tool used:** tau-argus 
**Version used:**  4.1.7 (build 4)
**Operating system used:** Windows

---

According to #44, one should "use `MAN(0)` to use given status and given safetyranges." Maybe there are other configurations, e.g. according to #65, "you could use `<READTABLE> 2` to allow for non-additivity."

I've also noticed a funny error message if you forget to specify the safety rule:

> Error in batch file
> Command: `<READTABLE>`
> TODO Add Automatic Use Status

I would suggest changing the error message as follows:

> Error in batch file
> Command: `<READTABLE>`
> `<SAFETYRULE>` required

The following appears to be the set-up necessary for data which is already in tabular shape:

```xml
<OPENTABLEDATA> "full data path here"
<OPENMETADATA> "full data path here"

<SPECIFYTABLE> "your table specification here"
<SAFETYRULE> MAN(0)    // or specify any other safety rules here

<READTABLE>    // allowed arguments are: nothing (documented), 1 (documented), 2 (see issue 65) 
```

**Comment by ppdewolf** [comment]
The funny error message
> TODO Add Automatic Use Status

is just a reminder for the developers 😄 and indeed looks funny to users

As mentioned in #120 we should update the manual (but time...and resources... 😞)

**Comment by g3o2** [comment]
Thank you! Actually, I have put it up as an issue also for documentation purposes, i.e. for any future users who are looking through the issues - as a complement to the manual so to speak ;-)

**Comment by ppdewolf** [comment]
Perfect! That's the way we intended to have this repo work! 👍
