### ISSUE TITLE
Modular appears to seldomly take into account low cost cells when specified in batch mode

### ISSUE THREAD

**Issue by g3o2** [sdcTools/UserSupport#123]
**SDC tool used:** tau-argus  
**Version used:**  4.1.7 (build 4)
**Operating system used:** Windows

---

_We are facing a significant issue with tau-Argus OS's Modular algorithm in a statistical production setting. Unfortunately, we are unable to reproduce the observed undesired behaviour in a staged scenario. Nevertheless, the behaviour appears worrying enough for us to post an issue on it here._

In a __table with a single hierarchical dimension having several levels (e.g. NACE)__ and for obvious scenarios (one primary confidential cell), cells to which we allocate a low cost via history file are not often, if at all, taken into account for secondary suppression. Actually, quite the contrary happens: often, we have to allocate a huge cost value to several other cells instead, because tau-Argus appears to systematically avoid the cell to which we have allocated a low cost.
This behaviour is inconsistent with tau-Argus version 3, where the same scenario with the same history file would produce the desired pattern.

When specifying the cost interactively via the "Set cost" button, the desired low cost cells are sometimes taken into account and other times not. However, when set via batch mode, they are rarely taken into account for secondary suppression. By batch mode, we refer to the "Open Batch Process", not the command line version of it.

**Comment by ppdewolf** [comment]
What Solver are you using? XPress, Cplex or Free Solver?

**Comment by g3o2** [comment]
XPress Solver.

**Comment by g3o2** [comment]
@ppdewolf Maybe the above weird behaviour is linked to the hitas bug that you mentioned in issue #124 ?

**Comment by ppdewolf** [comment]
Is this now solved with the new dll that was released in relation to #124 ?

**Comment by ppdewolf** [comment]
If not, could you make an example?

**Comment by g3o2** [comment]
Hi @ppdewolf, it looks better with the new dll. As regards coming up with an example, I’ve already tried, however it is close to impossible to reproduce the issue with tables which are too simple.
