### ISSUE TITLE
Modular produces non-deterministic confidentiality patterns for two dimensional tables

### ISSUE THREAD

**Issue by g3o2** [sdcTools/UserSupport#124]
**SDC tool used:** tau-argus 
**Version used:**  4.1.7 (build 4)
**Operating system used:** Windows

---

_We are facing a significant issue with tau-Argus OS's Modular algorithm in a statistical production setting. Unfortunately, we are unable to consistenly reproduce the observed undesired behaviour in a staged scenario. Nevertheless, the behaviour appears worrying enough for us to post an issue on it here._

In a table with two dimensions, one of which hierarchical having several levels (e.g. NACE) and the other being a simple dimension (e.g. employment size class), tau-Argus OS produces non-deterministic results as soon as we provide a history file containing cost adjustments and when run interactively. One run, tau-Argus closes one cell, in the other run then another instead, and so forth.

When run in batch mode (Open batch process), tau-Argus OS more often produces deterministic results but unfortunately not always.

The above behaviour makes using tau-Argus OS in an iterative setting very difficult (with each iteration risking to be different) and renders it almost useless for production purposes. 

This behaviour is also inconsistent with tau-Argus version 3, where results were always deterministic, at least as far as our statistical production tables were concerned.

**Comment by ppdewolf** [comment]
What Solver are you using? XPress, Cplex or Free Solver?

**Comment by ppdewolf** [comment]
There was a bug in tauhitas.dll that was fixed in a new version of tauhitas.dll (see [tauhitas.dll version 4.2.4.1](https://github.com/sdcTools/tauhitas/releases/download/4.2.4.1/tauhitas.dll))
Please try the same with the tauhitas.dll in your tau-argus directory replaced by this newer one.

**Comment by g3o2** [comment]
@ppdewolf Thank for your feedback! We are using XPress Solver - a new version will be deployed soon. Meanwhile, I will already test the tauhitas.dll.

**Comment by g3o2** [comment]
@ppdewolf Unfortunately, replacing the `tauhitas.dll` in the installation folder by the one here above produces the following error when running the solver:

```generic
Error in modular suppression procedure
JJ Routines: XP licence error
```

No error is reported by tau-Argus when using the original dll that came with the build version specified in my first post.

Tested with XPress Solver 8.6 (Xpress Optimizer 34.01.03).

**Comment by ppdewolf** [comment]
Could you look in the %TEMP% directory for a `XPerror.log` file?

**Comment by g3o2** [comment]
Here is the contents of the said file:

> Xpress licensing error 259: This is an OEM license but no OEM number was specified. This license may only be used in software from 'Statistics Netherlands for tau-Argus'. If you are an end-user please contact your software vendor, mentioning this error me

**Comment by g3o2** [comment]
Dear @ppdewolf, do you have any update on this issue ?

**Comment by ppdewolf** [comment]
It might be that I incorrectly compiled the dll without the OEM key. 
Try the one attached.
[tauhitas.zip](https://github.com/sdcTools/UserSupport/files/3879207/tauhitas.zip)

Because we are now open source, the new policy of FICO (Xpress) is to no longer give an OEM licence to tau-argus users, but to provide a "normal" licence. They still provide a discount if you only use it for tau-argus, but that is nowadays handled through a signed warrent. 
So I need to be aware of compiling the sources "the old fashioned way" to facilitate users taht still have the OEM-licence. And sometimes I forget... ☹️

**Comment by g3o2** [comment]
Thank you! At first glance, this dll appears to work. Consequently, we will test it here and check whether this dll would resolve the issue here above.

**Comment by ppdewolf** [comment]
No comments or feedback since new dll. Closng this issue for now.

**Comment by g3o2** [comment]
@ppdewolf Preliminary testing appears to show that the issue is not solved with the new dll, however, before reopening the issue we will get back with more detailed feedback to you. Setting up the test conditions is no easy feat.

a little note: it would great to have some artificial tables/datasets available for testing on github, so that users here could provide you with some code-backed or data-backed feedback. The difficulty resides in coming up with useful datasets which are not real world ones.

**Comment by ppdewolf** [comment]
All releases of tau-argus contain a data-subdirectory with some artificial datasets. They might figure as a first start?

**Comment by g3o2** [comment]
Interesting, in particular the dataset `vars1to5sampleG`.

Thank you for drawing our attention to this point. We will check whether the behaviour can be reproduced on those datasets.

**Comment by g3o2** [comment]
Current state is that the new dll did not solve the above issue. We will try to come up with a reproducible example for your convenience, if possible.
