### ISSUE TITLE
Different computation of cells

### ISSUE THREAD

**Issue by tenderle** [sdcTools/UserSupport#127]
**SDC tool used:** sdcTable and cellKey  
**Version used:**  0.28 and 0.17.2
**Operating system used:** Windows

---
Hi @bernhard-da,

[attached](https://github.com/sdcTools/UserSupport/files/3583616/insconsistency_sdcTable_cellKey.zip) you will find some R-objects to replicate my issue: Applying the functions `makeProblem()` and `ck_setup()` on the same data and identical dimension information created by `sdcHierarchies`, I got a different amount of cells,

```

library(cellKey)

tab <- ck_setup(
  x = dat,
  rkey = "rkey",
  dims = dimList,
  w = NULL,
  countvars = NULL,
  params_cnts = params_cnts
)

print(tab)


# create a problem instance 
prob <- makeProblem( 
  data = dat, 
  dimList = dimList, 
  numVarInd = NULL 
) 

print(prob)

```

The `cellKey` package computes all possible cells even if there are redundant information. Is it possible to state, that `makeProblem()` does the same?

Best,
Tobias

**Comment by bernhard-da** [comment]
hi @tenderle 

`sdcTable` also computes the redundant information but only displays it either

- case1: after protecting a dataset via `protectTable()` and returning the final protected table
- case2: via `sdcProb2df()` and setting argument `addDups=TRUE`

```# using your attached data-set
load("insconsistency_sdcTable_cellKey.RData") # --> prob as sdcTable obj

# cellkey
tab$perturb("total")
nrow(tab$freqtab(v = "total")) # 1176

# case 1:
res <- sdcTable::protectTable(prob, method = "SIMPLEHEURISTIC")
nrow(sdcTable::getInfo(res, "finalData")) # 1176

# case 2:
nrow(sdcTable::sdcProb2df(prob, addDups = TRUE)) # 1176
```

**Comment by tenderle** [comment]
Ok, thx @bernhard-da, 

my real purpose of this issue is connected to issue #128. Since `print(prob)` results in 
```
The object is an 'sdcProblem' with 1008 cells in 3 dimension(s)!
```
also `writeJJFormat()` will produce a jj-table that consists of 1008 cells. Anyway, that's even better since the instance is much smaller and the computation with either CTA or Intervalle faster.

However, using the following workaround (based on the `strID` as mentioned in #128) I can attach the result of the external SDC tool (CTA/Intervalle) to the initial `cellKey` object:
```
load("insconsistency_sdcTable_cellKey.RData")

# create peturbed freqs (including the dups due to cellKey)
library(cellKey)
tab$perturb("total")
tab_pert_withDups <- tab$freqtab(v = "total", type="unweighted")

# assign `strID` (from sdcTable) to perturbed tab (from cellKey)
strID_withDups <- sdcTable::sdcProb2df(prob, addDups = TRUE)$strID
tab_pert_withDups$strID <- strID_withDups

# create the jj-Format
inp <- sdcTable::createJJFormat(prob)

# replace the freqs in the `inp` object (sdcTable) by the perturbed freqs (from cellKey)
dups <- duplicated(strID_withDups)
inp[[3]]$freqs <- tab_pert_withDups[!dups]$puwc

# write modified `inp` to JJ-file
sdcTable::writeJJFormat(inp, path="out.jj")

# external step by a further sdc Tool that uses the jj-file

# assume the solution of the further tool is frequency times 100
sol <- inp[[3]]$freqs * 100
sol <- data.table(strID=strID_withDups[!dups], sol)

# assign the solution to the cellKey table
tab_new <- merge(tab_pert_withDups,sol, by="strID")
tab_new[puwc != sol/100]
```
I think that is the solution I was looking for ... as long as the order of the cells in `cellKey` and `sdcTable` (with dups) remains identical?

Best, 
Tobias

**Comment by bernhard-da** [comment]
hi @tenderle 

yes, the order will always be the same as in `cellKey`, also `sdcTable::makeProblem()` is used to build the (complete) table.

**Comment by tenderle** [comment]
Perfect, thx again.
