### ISSUE TITLE
Index of writeJJFormat()

### ISSUE THREAD

**Issue by tenderle** [sdcTools/UserSupport#128]
**SDC tool used:** sdcTable  
**Version used:**  0.28
**Operating system used:** Windows, Linux

---
Hi @bernhard-da ,

when I use `writeJJFormat()` there is the column `ind` that is needed for other tools that use the jj-file as input. The order of the initial table is different to the order of this jj-table. 

If I want to merge the result of such a further tool (cta or intervalle) with the initial table of `sdcTable` I can't do this due to a missing mapping indicator. Or is there a mapping indicator?

Best,
Tobias

**Comment by bernhard-da** [comment]
let's use an simple example:

```
rm(list = ls())
library(sdcTable)
data("microData1", package = "sdcTable")
dl <- list(
  region = hier_create(root = "Total", nodes = LETTERS[1:4]),
  gender = hier_create(root = "Total", nodes = c("male", "female")))

prob <- makeProblem(
  data = microData1,
  dimList = dl,
  numVarInd = "val")

inp <- createJJFormat(prob)
```

the third element of `inp` is the `data.table` with colum `ind`. incrementing this variable by `1` returns the indices within `prob@problemInstance`

check:
```
freqs <- prob@problemInstance@Freq
index <- inp[[3]]$ind + 1
all.equal(freqs, freqs[index]) # TRUE
```

it is also the same order you get from
```
df <- sdcProb2df(prob, addDups = FALSE) # the addDups = FALSE is important in this case!
all(df$freq == freqs) # TRUE
```

and from `df` you can also use for example `strID` as id for the cells ...

**Comment by tenderle** [comment]
Thx, @bernhard-da, 

the `strID` variable is what I was looking for. I can use it as mapping indicator. The reason why I have observed inconsistencies and non-matching freqs regarding the jj-file and the `cellKey` object (and not the `sdcTable` as I mentioned here, sorry for that) is related to #127. However, the order of  the jj-file and the `sdcTable` object (without dups) is identical as you emphasised. I will continue the discussion in issue #127.

Best, 
Tobias
