### ISSUE TITLE
Perturbed weighted counts

### ISSUE THREAD

**Issue by tenderle** [sdcTools/UserSupport#129]
**SDC tool used:** cellKey  
**Version used:**  0.17.101 and 0.17.2
**Operating system used:** Windows

---

Hi @bernhard-da,

in my example  from issue #127 using NO weights, the `pwc` has wrong counts. 

```
load("insconsistency_sdcTable_cellKey.RData")

library(cellKey)
print(tab)
tab$perturb("total")
res <- tab$freqtab(v = "total")
res[,diff:= pwc-puwc]
table(res$diff)
```
However, when I run the following afterwards, `pwc` is computed correctly
```
tab <- ck_setup(x = dat, rkey = "rkey", dims = dimList, w = NULL)
params <- ck_params_cnts(D = 5, V = 3, js = 2, pstay = 0.5)
tab$params_cnts_set(params, "total") 

tab$perturb(v = c("total"))
res2 <- tab$freqtab(v = c("total"))
res2[,diff:= pwc-puwc]
table(res2$diff)
```
Is this due to different versions of the `cellKey` package? I may have used the first `ck_setup()` (loaded from the RData-file) with a different version than the second time?

Line 706 of the file `cellkey_pkg.R` states
```
pwc <- newtab[[col_puwc]] + newtab[[col_wcavg]]
```
Is it possible, that the average weight is `1` (?) and, hence, a one is added to each cell larger than zero. That is, `puwc = pwc + 1` if `pwc > 0`. 

Best,
Tobias

**Comment by bernhard-da** [comment]
hi @tenderle, thx for spotting. i have already fixed this in the next-branch in https://github.com/sdcTools/cellKey/commit/7d4cac15b4f35fb5866aad4041a98ee4457f6dfe

this branch (where i am currently working to implement also the magnitude-perturbation) can be installed with `devtools::install_github("sdcTools/cellKey", ref = "next")`

**Comment by tenderle** [comment]
Ah ok, than I used the master branch first and then the version with the fix.

I'm going to update the package within next days/weeks. First I will wait until we have our webex on Wednesday.
