### ISSUE TITLE
Modular changes flags from Unsafe (Manual) to Safe (Manual)

### ISSUE THREAD

**Issue by gosiagit** [sdcTools/UserSupport#130]
**SDC tool used:** Tau-argus
**Version used:** TauArgus4.1.16BETA
**Operating system used:** Windows

---
Hello, I run TauArgus from a batch file with the following settings:
```
<CLEAR>
<OPENTABLEDATA> "data_table_X"
<OPENMETADATA> "rda_table_X"
<SPECIFYTABLE> "Code""REF_AREA"|"Value"|"Value"|"CostVar"
<SAFETYRULE> MAN(15)
<READTABLE> 1
<SUPPRESS> MOD(1,60,1,1,1) 
<WRITETABLE> (1,2,AR+AS+FL+TR+,"output_table_X")
```

It seems that for some observations (at a higher hierarchy levels) after running the batch file the status is changed:
- from 9 - Unsafe (Manual) to 2 -Safe (Manual)
- from 10 - Protected to 2 -Safe (Manual)

This is surprising - especially the first case. What could be the reason behind and how to fix it?

**Comment by ppdewolf** [comment]
This is indeed strange. I understand that the suppression was applied (i.e. secondary suppression were there) but in the output file some primary unsafe cells were set to safe? Is there any info in the log-file?

But difficult to see what the problem could be without an example. Could you construct an example table where this happens?

**Comment by gosiagit** [comment]
Hi Peter-Paul, I had large complex tables and I tried to find if there is possible non-additivity which causes it. However, the problem seem stemming from decimals. 

Illustrating it on a simple example - [test_git.zip](https://github.com/sdcTools/UserSupport/files/3881102/test_git.zip):
- I prepared two versions of data_test: i) first breakdown have numbers with 3 decimals,  ii) in the other there are just integers. I run it using batch file go_batch (with default name: data_test). With non-integers the flag from the total XX.1 changes from Unsafe 9 to Safe 2. 
- I run it with two option in .rda file: DECIMALS 3 and 20. The file "go_output_tab1 decimals deci 20 - flag change from 9 to 2" shows the issues with rounding. 
- Please note that I run the batch file with setting: "<READTABLE> 1 " - I presume it indicates 'compute incorrect totals'. 

I hope it clarifies the problem. Would you know how to fix it? 
Thank you!
Gosia

**Comment by ppdewolf** [comment]
Looks like it does actually have to do with the non-additivity. Please change the Total to 1072.444 and run again. Then the correct flag for XX.1 is used.

The fact is, when using "make additive", the rule is that only at the lowest level the status is kept as is (these values will not be changed by making the table additive). When changing higher level cells (e.g. the XX.1 cell) it is not clear how the status should be afterwards. This is also mentioned in the manual on page 95: 

> There is an option to calculate the possibly missing marginals and totals. This option should be used only as an emergency. ... When t-argus has to compute these marginals all safety information will be ignored.

**Comment by ppdewolf** [comment]
As a work around you can do the following when using maual status (as you do in your example):

- Make an apriori file (`.hst`) with the status for the cells, based on your original table (`.tab`)
- Import the table (`.tab`) into tau-ARGUS
- Make your table additive
- Import the apriori file (`.hst`) into tau-ARGUS
- Run your favourite protection method 😄

**Comment by ppdewolf** [comment]
No more comments after workaround, so closing the issue for now.
