### ISSUE TITLE
Error in LinkedTable/Batch

### ISSUE THREAD

**Issue by EckhardJ** [sdcTools/UserSupport#134]
**SDC tool used: tau-argus 
**Version used: 4.17 
**Operating system used: Windows 10 64bit
---
I am trying to protect two linked tables with free modular method in Batch, error in tempTot.rda but the tempTot.arb file is OK (i give you all Meta-Data but no MicoData). Where is the mistake ?
 
[Error in LinkedTable.zip](https://github.com/sdcTools/UserSupport/files/3868318/Error.in.LinkedTable.zip)

**Comment by ppdewolf** [comment]
Does this also happen in interactive mode?

**Comment by EckhardJ** [comment]
Yes, also in interactive mode, in the file is a report of an little java-error by starting the batch in GUI with included supress.
[Fehler_LinkedTable_Gui.txt](https://github.com/sdcTools/UserSupport/files/3879270/Fehler_LinkedTable_Gui.txt)

**Comment by ppdewolf** [comment]
A previous "bugfix" caused this behaviour. I removed that bugfix.
In the next release (most likely at the end of this month) it will be corrected.
