### ISSUE TITLE
detectSingletons not solving sdcTable problem

### ISSUE THREAD

**Issue by olangsrud** [sdcTools/UserSupport#135]
*Please specify*  
**SDC tool used:** sdcTable
**Version used:**  0.30
**Operating system used:** Windows

---

It seems that problems with two singletons are solved by 
`detectSingletons = TRUE`, but not three singletons.

The problem was detected by my college @krlono. The dataset is also from him. See the code below.

```
library(sdcTable)

# Input data
z <- data.frame(values = c(1, 1, 7, 1, 0, 1, 0, 0, 2, 8), 
                var1 = rep(1:2, each = 5), 
                var2 = c("A", "B", "H", "M", "W"), stringsAsFactors = FALSE)

# Defining hierarchies 
dimList <- list(var1 = data.frame(levels = c("@", "@@", "@@"), 
                                     codes = c("Total", "1", "2"), 
                                     stringsAsFactors = FALSE),
                var2 = data.frame(levels = c("@", "@@", "@@", "@@", "@@", "@@"), 
                                       codes = c("Total", "A", "B","H","M","W"), 
                                       stringsAsFactors = FALSE))

# makeProblem and primarySuppression in sdcTable
problem <- makeProblem(z, dimList, dimVarInd = 2:3, freqVarInd = 1)
primary <- primarySuppression(problem, type = "freq", maxN = 2)

# Secondary suppression
protected <- protectTable(primary, method = "SIMPLEHEURISTIC", detectSingletons = TRUE)

# Look at output
print(getInfo(protected, type = "finalData"))

# When var1 is 1, it is easy to find out that the three protected values must be 1,
# since their sum is 3.

# If we set the values of "A" in the data to 0,
# it seems that detectSingletons = TRUE solves the problem  
z$values[z$var2 == "A"] <- 0
```

**Comment by bernhard-da** [comment]
@olangsrud and @krlono thx for reporting. it will take however a bit until i have time to look into this.

**Comment by bernhard-da** [comment]
@olangsrud  and @krlono i just had a look and i am not sure, if this is indeed a "bug" as it would require two of the three units to work together to learn the values of the third one (this is a count-table). furthermore, the suppressed numbers could also be 0 or 2 ... 

@ppdewolf: do you protect against three singletons in one dimension in tau-argus?

**Comment by olangsrud** [comment]
>  furthermore, the suppressed numbers could also be 0 or 2 ...

As I understand it, the suppressed numbers could not be 0 or 2 since all zeros are primary safe and it seems that zeros are never secondary suppressed.

Note that a related problem occur with parameter `allowZeros = TRUE` as input to `primarySuppression`.  This can be seen by changing input data:

```
z$values <- c(0, 0, 7, 0, 9, 0, 9, 9, 2, 8)
# When var1 is 1, it is easy to find out that the three protected values must be 0,
# since their sum is 0.
```

**Comment by ppdewolf** [comment]
In tau-argus you have the following options: (row = 1 dimension)

- additionally protect two singletons in a row
- make sure that the number of suppressed contributors in a row is satisfying the threshold rule
- additionally protect a singleton and another primary unsafe cell with more than one contributor

These options were intended to be used in case of magnitude tables, not in frequency count tables, even though it is possible to select them in either case.

The second option would come close to pretecting three singletons if the threshold rule would request at least 4 contributors.

**Comment by bernhard-da** [comment]
@ppdewolf  thx for your inputs, i really like the threshold idea and this is what i have now implemented. 

therefore, I have added a `threshold` argument to `protectTable`

```
protectTable(p, method = "SIMPLEHEURISTIC", detectSingletons = TRUE, threshold = 4)
```

using this approach you would be (imo) able to fix both problems (also the one with the suppressed empty cells). `detectSingleton = TRUE` makes sure that the same singleton-detection algorithm as in previous versions is run. Setting `threshold` makes sure that in each "row", additional cells are possibly suppressed so that at least `threshold` contributors are suppressed in total. If `threshold` is not specified, these checks are not run. Also, one can only run the threshold part by specifiying a number while omitting the singleton-part

```
protectTable(p, method = "SIMPLEHEURISTIC", threshold = 4)
```
@olangsrud it would be great if you could test this before I push a new version to cran.

**Comment by olangsrud** [comment]
I still haven’t found out how to build/compile this on my windows-computer. Can you make a windows-zip?

**Comment by bernhard-da** [comment]
@olangsrud i just built with win-builder. you can find the zip [`here`](https://win-builder.r-project.org/zLk0v5kDor9n/sdcTable_0.30.1.zip)

**Comment by olangsrud** [comment]
Thanks! I will test.

**Comment by olangsrud** [comment]
Thank you for the new version. I have looked at several examples and it seems to work without errors or strange results.

Now it possible to avoid the problems described above. When using `allowZeros = TRUE` it seems that the problem, in general, is solved by using `threshold = 1`.

With `allowZeros = FALSE` it seems that `threshold = 3` is equivalent to `detectSingletons = TRUE`. The problem in the above example is solved by `threshold = 4` as you mention.

In general, it is not difficult to generate examples that require higher thresholds. In practise it is difficult to recommend a specific value. A negative consequence of too high values is extra suppression of cells not involved in singleton problems.

Ideally,  `when allowZeros = FALSE`, a re-definition of `threshold` would have been better: At least `(threshold + "number of suppressed cells")`  contributors are suppressed in total. Then, `threshold = 1` would solve the problem similarly for both values of `allowZeros`.

Anyway, the new version solves a lot of problems.

**Comment by olangsrud** [comment]
@bernhard-da I think it is time to remove the awaiting_feedback-label. I have given feedback, but I don’t have access to remove the label  myself.

**Comment by bernhard-da** [comment]
sure, the update is already in the latest version that is on cran.
