### ISSUE TITLE
(n, k)-dominance rule : n=1, weighted variables

### ISSUE THREAD

**Issue by MaximeBeaute** [sdcTools/UserSupport#139]
**SDC tool used:** sdcTable
**Version used:**  0.31
**Operating system used:** Windows

---
 
Hi ! I am from the French NSI. I have a couple of questions about the (n, k)-dominance rule with the package sdcTable.

1/ In our NSI, we usually use the (1, 85) dominance rule. When I try to use it, I get the following error message `Parameter 'n' must be >= 2 for nk-dominance rule.`. Is there a specific reason why you disabled this use case ? Is there a workaround ?
    
    
2/ In the changelog of version 0.31, it is written `[todo] check dominance rules (unweighted variables are used)`. Is this feature implemented, or will it come in a future version ?
When I run the code below, if I am correct, I should get the same result with unweighted and weighted data : the cell should be primarily suppressed due to the (2, 90)-dominance rule in both dataset. Yet, the method primarySuppression() seems to incorrectly consider safe the cell in the weighted data.

```
# R version 4.0.0 (2020-04-24)
# Rcpp version 1.0.4.6
# shinythemes version 1.1.2
# sdcHierarchies version 0.18.2
# sdcTable version 0.31
library(sdcTable)


dim.month <- data.frame(
  levels=c('@'),
  codes=c('may'),
  stringsAsFactors=FALSE)

# Unweighted version: correct
dataUnweighted <- data.frame(
  month = rep('may',10),
  type = c('A','A','B','B','C','C','D','D','D','D'),
  sales = c(91,91,3,3,4,4,1,1,1,1))

problemUnweighted <- makeProblem(
  data=dataUnweighted,
  dimList=list(month = dim.month),
  dimVarInd=1,
  freqVarInd=NULL,
  numVarInd=3,
  weightInd=NULL,
  sampWeightInd=NULL)

problemUnweighted <- primarySuppression(problemUnweighted, type='nk', n=2, k=90, numVarName="sales")
cellUnweighted <- sdcProb2df(problemUnweighted, addDups=TRUE, addNumVars=TRUE, dimCodes="original")
cellUnweighted

# This cell is effectively unsafe using the (2, 90)-dominance rule :
(max(dataUnweighted$sales)*2)/sum(dataUnweighted$sales)


# Weighted version: uncorrect
dataWeighted <- data.frame(
  month = rep('may',4),
  type = c('A','B','C','D'),
  sales = c(91,3,4,1),
  weight = c(2,2,2,4))

problemWeighted <- makeProblem(
  data=dataWeighted,
  dimList=list(month = dim.month),
  dimVarInd=1,
  freqVarInd=NULL,
  numVarInd=3,
  weightInd=NULL,
  sampWeightInd=4)

problemWeighted <- primarySuppression(problemWeighted, type='nk', n=2, k=90, numVarName="sales")
cellWeighted <- sdcProb2df(problemWeighted, addDups=TRUE, addNumVars=TRUE, dimCodes="original")
cellWeighted

# This cell should be unsafe using the (2, 90)-dominance rule :
(max(dataWeighted$sales)*2)/sum(dataWeighted$sales*dataWeighted$weight)
```

**Comment by bernhard-da** [comment]
hi @MaximeBeaute ; thx for the detailed issue-report that was indeed a bug that was fixed in https://github.com/sdcTools/sdcTable/commit/be61611ad6a3f01e2af5719d6af1224b1880bf28

**Comment by MaximeBeaute** [comment]
Thank you for fixing this issue !

What about my point n°1 ? (Next time I'll create one ticket for one question, I guess it will be clearer this way)

**Comment by bernhard-da** [comment]
@MaximeBeaute sorry about not answering before; i simply missed it and fixed in https://github.com/sdcTools/sdcTable/commit/3dd1a567bcf89a19a780e4d52f1f4dd26658e8aa 

using nk-rule with n=1 will be possible in the github-version and in the next cran version. i hope i find some time to update soon.

**Comment by MaximeBeaute** [comment]
Great ! Thanks again Bernhard !
