### ISSUE TITLE
Problem with hierachy files and Hypercube method

### ISSUE THREAD

**Issue by maximebergeat** [sdcTools/UserSupport#14]
SDC tool used: Tau-Argus
Version used: 3.5.0 build 27
Operating system used: Windows

My colleague and I got some trouble with hierarchy file attached in pull requests (what is the best option to post an issue?).
It is not possible to use the Hypercube method taking into account this hierarchy file.

We have noticed something weird: it's working if hierarchical variable contains 11 or 13 digits, but it's not working anymore when it contains 12 digits (like in toy microdata attached in pull request).

This problem arises also with Tau-Argus version 4.1 with some real French data, but for now we didn't manage to replicate it with toy data.

**Comment by ppdewolf** [comment]
I don't see any attachment? It is possible to attach files to issues though. See e.g., issue #1

**Comment by maximebergeat** [comment]
Attached one example with this issue.
Slight problem is that it is only possible to add .txt files (I don't manage to attache .asc or .rda files).

[test_microdata_hypercube_hrc_NotWorking#1_asc.txt](https://github.com/sdcTools/UserSupport/files/406616/test_microdata_hypercube_hrc_NotWorking.1_asc.txt)
[test_microdata_hypercube_hrc_NotWorking#1_rda.txt](https://github.com/sdcTools/UserSupport/files/406615/test_microdata_hypercube_hrc_NotWorking.1_rda.txt)
[hierarchy_test_NotWorking#1_hrc.txt](https://github.com/sdcTools/UserSupport/files/406617/hierarchy_test_NotWorking.1_hrc.txt)

**Comment by ppdewolf** [comment]
This seems to be the same as Issue #17.
Issue  #17 is solved and solution will be available in next release.
