### ISSUE TITLE
Bug in the tutorial 

### ISSUE THREAD

**Issue by Krisselack** [sdcTools/UserSupport#141]
*Please specify*  
**SDC tool used:** (sdcTable)  
**Version used:**  0.31.1
**Operating system used:** (Windows) 
---
Tutorial https://sdctools.github.io/sdcTable/articles/sdcTable.html (0.31.1)

Under the Creating objects of class sdcProblem for further processing
Lists are created with the name dimInfo; In the following function call and in the text, the object is referred to as dimList.

**Comment by bernhard-da** [comment]
hi @Krisselack  thx for spotting; fixed with https://github.com/sdcTools/sdcTable/commit/a6758761551a0c6eb3d84c608a4fbfaea1756c03
