### ISSUE TITLE
Linked tables weird error message

### ISSUE THREAD

**Issue by aicabrera** [sdcTools/UserSupport#142]
**SDC tool used:** tau-argus  
**Version used:**  4.2.0
**Operating system used:** Windows

---
I'm trying to protect two SBS tables with Linked tables -option. First table has nace (3 digit) and size class as explanatory variables and the second table has only nace (4-digit). Once I press the "suppress via modular" button I get the following error message: "Error running the cover table Returned value = 1". Has anyone any idea what is going wrong with the linked tables procedure? 

The tables are aggregated in tau-Argus from microdata so there are no additivity etc. issues. There is also no issue when I protect the tables separately. And, with previous version of tau-argus (4.1.7.) also the linked tables -option has worked fine with these tables.

**Comment by ppdewolf** [comment]
When I try your example with the test-data (vars1to5sampleG.asc) also using NACE (3digit) x Size and NACE (4 digit), things work smoothly at my PC.

Could you post the logbook.txt from your %TEMP% directory?

**Comment by aicabrera** [comment]
[log_linked.txt](https://github.com/sdcTools/UserSupport/files/4779700/log_linked.txt)
Here is the log file.

**Comment by ppdewolf** [comment]
Something you might try: add "." to your path (i.e. referencing the current directory). If it helps, I don't know why though...

Also a bit strange: in your log-file some lines appear twice, while they should appear only once (the info on the dll-versions).

**Comment by aicabrera** [comment]
Sorry, I'm not sure where I could try to add ".". Do you mean the path where my data and rda files (C:\Users\cabrera\Downloads) should contain a "."?

Some lines appear twice probably because I opened tau-argus twice (I was inpatient since it was opening so slowly ;-) )

**Comment by ppdewolf** [comment]
You should add it to you environment variable PATH. On a Windows machine you can find it by right clicking on "This PC" (or System?), choosing "properties", choosing "advanced system properties", choosing "environment variables". See attached screenshot (in Dutch unfortunately).
Hope this helps.

![Knipsel1](https://user-images.githubusercontent.com/19729987/84667674-f60cbc00-af22-11ea-96ae-2d7f7d575658.PNG)
![Knipsel2](https://user-images.githubusercontent.com/19729987/84667681-f86f1600-af22-11ea-8aed-6fcfe8b1d45e.PNG)
![Knipsel3](https://user-images.githubusercontent.com/19729987/84667686-fad17000-af22-11ea-9626-007967f08a29.PNG)
![Knipsel4](https://user-images.githubusercontent.com/19729987/84667695-fc9b3380-af22-11ea-8c24-95062ecbf30f.PNG)
![Knipsel5](https://user-images.githubusercontent.com/19729987/84667701-fe64f700-af22-11ea-9465-2fec92520a35.PNG)

**Comment by ppdewolf** [comment]
Solved. Turned out to be an issue with paths that contain spaces.
Workaround is available (see e.g., [here](https://sdctools.github.io/UserSupport/)) Or just don't install into a directory whose name contains space(s) 😄
