### ISSUE TITLE
does Audit still work ?

### ISSUE THREAD

**Issue by g3o2** [sdcTools/UserSupport#148]
**SDC tool used:** tau-argus  
**Version used:**  4.2.0 build 5
**Operating system used:** Windows
---

With a secondary suppression based on Modular (with Xpress solver), the Audit button no longer works correctly. When pushed, it shows the error message "0". I have checked with other suppression methods, same result.

**Comment by ppdewolf** [comment]
I cannot reproduce this. I applied Modular to table `Size x Region` from the `tau_testW.asc` dataset that is distributed with tau-argus, using the Xpress solver. Then, in my attempts, the `audit` works as it should.

The error message you mention: do you only get a window with "0"? Nothing else? What can be found in the `logbook.txt` en `Audit.log` files in your %TEMP% directory?

**Comment by g3o2** [comment]
Yes, only a window with "0". In the `logbook.txt`` , there is nothing ground breaking:

```
Start of TauArgus run
TauArgus version 4.2.0 build 5
ArgusLib.jar version 4.0.2 build 1
TauRounder.dll version 2.1.0.1
TauHitas.dll version 4.2.4.1
TauArgusJava.dll version 1.1.4.4
```

`Audit.log` does not exist in the %TEMP% directory. speculation: looks like it was not even initialised or like it failed to initialise.

Same non-working behaviour when testing with the aforementioned dataset `tau_testW.asc` (`Var1`, `Size` x `Region`).

**Comment by ppdewolf** [comment]
Do you have `Intervalle.exe` in your tau-argus directory?

**Comment by g3o2** [comment]
Yes, for `Intervalle.exe` and `Anneke.jj`. 
No, for `input_Audit.txt`.

**Comment by ppdewolf** [comment]
Sorry, should have been `Anneke.txt`. Could you post the content of `Anneke.txt` (if it exists)?

**Comment by g3o2** [comment]
Contents `Anneke.txt`:

```
%TEMP%Anneke.JJ
NoLongerNeeded
%TEMP%Anneke.Out
%TEMP%Anneke.txt
primsec
without
2
1
0
0
50
50
0
5
xpress
NoLicenceSpecified
```

Please note that, for Modular, we do use Xpress Solver (radio button in the options menu is on `Xpress`).

**Comment by ppdewolf** [comment]
Just to be sure: is the `%TEMP%` as it appears in that file, or did you replace the actual directory by this out of privacy? It should be a legitimate directory, so also ending with a `\`. (I.e. such that `%TEMP%Anneke.JJ` with the correct directory actually exists).

**Comment by g3o2** [comment]
I've replaced this on purpose out of privacy.

**Comment by ppdewolf** [comment]
Just a wild guess: have you installed tau-argus in `C:\Program Files (x86)`?
If so, could you try to install it under `C:\`?
It looks like my "fix" to be able to deal with UNC-paths broke the possibility of using directories with spaces in their name.

**Comment by ppdewolf** [comment]
Or replace the `ArgusLib.jar` in the lib subdirectory where tau-argus is installed bij the one in [this zip-file](https://github.com/sdcTools/UserSupport/files/5074573/ArgusLib.zip)

**Comment by g3o2** [comment]
@ppdewolf yes, the software is installed under `%PROGRAMFILES(x86)%`. Unfortunately, there is no way I can change this. I will try replacing the `jar` file and report back to you.

**Comment by g3o2** [comment]
So to report back: your `jar` file fixes the issue and audit works again thereafter.

**Comment by ppdewolf** [comment]
Great. Thanks for letting us know it works with that `jar` file.
