### ISSUE TITLE
linked table error message

### ISSUE THREAD

**Issue by yilingsg** [sdcTools/UserSupport#152]
**SDC tool used:** tau-argus
**Version used:**  4.2.0 Build 5
**Operating system used:** Windows

---
Hello, I am following Manual V4.1 Section 4.5.2 Linked Table and encounter the error "Error running the cover table. Returned value: 1". I searched online and found a similar issue at https://github.com/sdcTools/UserSupport/issues/142 and had tried the solution (add "." to path). However, I am still getting the same error. Would you mind helping to take a look please? Attached screenshot and logbook. Thank you very much!
[github_tau_linkerror.docx](https://github.com/sdcTools/UserSupport/files/5236894/github_tau_linkerror.docx)

**Comment by ppdewolf** [comment]
Hi,
I guess this is due to the fact that for one of the tables you did not specify any safety-rule. When using Linked Table approach, all tables should be using the same sensitivity rules. Otherwise you might end up with inconsistencies.

**Comment by yilingsg** [comment]
[github_tau_linkerror02.docx](https://github.com/sdcTools/UserSupport/files/5237601/github_tau_linkerror02.docx)

**Comment by ppdewolf** [comment]
Other possible reason could be that you are using directories with spaces in their names. See final comment to #142 :

> Solved. Turned out to be an issue with paths that contain spaces.
> Workaround is available (see e.g., [here)](https://sdctools.github.io/UserSupport/) Or just don't install into a directory whose name contains space(s) 😄

**Comment by yilingsg** [comment]
indeed so! i moved it to a directory without spaces and it worked. thanks a lot! may i know is there anywhere where i can see the cover table that was mentioned in the manual?

**Comment by ppdewolf** [comment]
intermediate files can be found in the %TEMP% directory. The covertable (and meta) that is used for input is `tempTot.*`

**Comment by yilingsg** [comment]
noted. thank you very much!
