### ISSUE TITLE
Sign up as a Member of the User Group

### ISSUE THREAD

**Issue by surfing-in-the-sun** [sdcTools/UserSupport#155]
To sign up to be a member of the User group of SDCTools, you need to follow these instructions.

1) Sign up on Github OR Sign in if you already have an account

2) Please write below: 

`Asking for Permission to be Member of the User Group`

 You will be added and receive an confirmation E-Mail after that.

  You will receive notifications about news, releases and User Group Activities as they come up.

**Comment by sub-sub-starfish** [comment]
Asking for Permission to be Member of the User Group

**Comment by vanessa-azzopardi** [comment]
Asking for Permission to be Member of the User Group

**Comment by hadjittofis** [comment]
Asking for Permission to be Member of the User Group

**Comment by jeroenborghuis** [comment]
Asking for Permission to be Member of the User Group

**Comment by JJ585** [comment]
Asking for Permission to be Member of the User Group

**Comment by olangsrud** [comment]
Asking for Permission to be Member of the User Group

**Comment by KarinaKelleher** [comment]
Asking for Permission to be Member of the User Group,
Thanks Karina (karina.dineen@cso.ie ; UserName : KarinaKelleher)

**Comment by OlesjaN** [comment]
Asking for Permission to be Member of the User Group.

**Comment by rvdlaar8** [comment]
Asking for Permission to be Member of the User Group

**Comment by tdlinehancso** [comment]
Asking for permission to be Member of this User Group

**Comment by HakonTorfinnKarlsen** [comment]
Asking for Permission to be Member of the User Group

**Comment by reynirlg** [comment]
Asking for Permission to be Member of the User Group

**Comment by spiliopv** [comment]
Asking for Permission to be Member of the User Group

**Comment by AnceCer** [comment]
Asking for Permission to be Member of the User Group

**Comment by akselthomsen** [comment]
Asking for Permission to be Member of the User Group

**Comment by akselthomsen** [comment]
Asking for Permission to be Member of the User Group

**Comment by akselthomsen** [comment]
Asking for Permission to be Member of the User Group

**Comment by robindraprabhu** [comment]
Asking for Permission to be Member of the User Group

**Comment by MarianNecula** [comment]
Asking for Permission to be Member of the User Group

**Comment by zane-mat** [comment]
Asking for Permission to be Member of the User Group

**Comment by JanPestun** [comment]
Asking for Permission to be Member of the User Group

**Comment by borisfrenkie** [comment]
“ Asking for Permission to be Member of the User Group “

**Comment by BeataNagy** [comment]
Asking for Permission to be Member of the User Group

**Comment by Alicia-ES** [comment]
Asking for Permission to be Member of the User Group

**Comment by kristilehto** [comment]
Asking for Permission to be Member of the User Group

**Comment by agalvezmo** [comment]
Asking for Permission to be Member of the User Group

**Comment by Incarro** [comment]
“ Asking for Permission to be Member of the User Group “

**Comment by GiacomoCarli** [comment]
Asking for Permission to be Member of the User Group.

**Comment by danlupp** [comment]
Asking for Permission to be Member of the User Group

**Comment by hegemb0** [comment]
Asking for Permission to be Member of the User Group

**Comment by Kyoshido** [comment]
Asking for Permission to be Member of the User Group
