### ISSUE TITLE
Error in SetVariable: variable HHID

### ISSUE THREAD

**Issue by vanessa-azzopardi** [sdcTools/UserSupport#159]
Hi,

I have recently upgraded from an older version of muArgus (version 3 I believe) to version 5.1.5 and I have been encountering an issue whenever I try calculating the risk tables.  Once I reach Specify -> Combinations, add the variables and try to calculate the tables, I get an error message saying that there is an error in the HHID (household identifier) variable.

The exact wording of the error message is: Error in SetVariable: variable HHID.

I'm stuck trying to figure out what is wrong with this variable.  I tried setting this variable as an HH Identifier and as an Other variable with identification level of 0 (so that it is ignored) but the outcome was the same...in both cases I got the same error.  Any ideas please?

Here is a snippet of the contents of the HHID variable:
HHID
101000
101001
101002
101006

**Comment by ppdewolf** [comment]
What version is the older one? 5.1.3? 
Did you try using the same data and same metadata in 5.1.3?

**Comment by vanessa-azzopardi** [comment]
Hi Peter Paul,

Thanks for transferring.  Didn't realise I was in the wrong place.

To provide an update, the issue has been resolved now.  The problem was coming from 2 missing commands in the metadata file, i.e. the following:
<SEPARATOR> ","
<NAMESINFRONT>

Basically if the metadata file is generated from MuAurgus (choosing the free with meta option) and then saved, these mentioned commands do not show up in the metadata file.  Similarly, if a prepared metadata file is used and then updated in MuArgus, upon saving the metadata file, the mentioned commands are removed from the text file each time.  When they are re-added manually to the metadata file, it works fine.

**Comment by ppdewolf** [comment]
Thanks for the update.
Good that you noticed that the commands are somehow not saved when saving metadata from within mu-argus. That is indeed a bug that I will try to solve in a next release.

I will add the label "workaround" to this issue for now. Thanks.

**Comment by vanessa-azzopardi** [comment]
You are welcome and thanks for your help.

I also noticed that when saving the output file (safe file), the headers (variable names) are missing in the generated file.  The parameters I was using are: entropy for suppression and keeping the HH identifier in the safe file.

On another note, when the risk tables are calculated, cases where there less than the threshold value of missing cases are flagged in red.  Mu Argus also doesn't seem to distinguish between the values which were originally set to missing and those converted to missing by Mu Argus itself.  I'm not sure if this behaviour was the same for the older version but I think that missing cases should not be flagged given that the value is by default suppressed.  Not sure what you think.

**Comment by ppdewolf** [comment]
If I understand you correctly: it is actually one of the features of suppression as a method, that it should not be obvious to users whether a missing value is due to the SDC or due to "ordinary missing at data collection". That's why the resulting dataset (with additional missings) has the same value for missing in both cases. I.e., loading a protected dataset (with suppression) into mu-argus gives the incorrect results concerning unsafe combinations, since it cannot distinguish anymore between the two cases (on purpose).
However, when I calculate the combinations, missing codes are always red. Red only indicates that it concerns the missing value, not that it is unsafe (in tau-argus a red cell _does_ mean unsafe, in mu-argus not). See (code 9 is "missing"):

![Knipsel](https://user-images.githubusercontent.com/19729987/108197027-1e843000-711a-11eb-851a-86576ce2f9e4.PNG)

**Comment by vanessa-azzopardi** [comment]
I see, thanks for clarifying regarding red cells.

I fully agree with you about not distinguishing between missing due to suppression and ordinary missing being a feature of the suppression method.  What I meant was that within Mu Argus, this distinction seems to be made (i.e. there are separate rows for the two kinds of missing), as shown below. 

![image](https://user-images.githubusercontent.com/75853527/108199310-18dc1980-711d-11eb-8be9-bc7d05e9cfc5.png)


In my case, the threshold was set to 2.  The only issue here is that because there is only 1 case of missing (-1), I get an unsafe combination in dimension 1 for BIRTHPLACE_imp.  In reality, the first row of missing poses no risk because it is actually the same as if the value was suppressed in MuArgus.

**Comment by ppdewolf** [comment]
This is strange. When I use -1 as missing and include one record with -1, I get this:
![afbeelding](https://user-images.githubusercontent.com/19729987/108205317-31503200-7125-11eb-80c3-0bf46d102322.png)

Are you sure that the two "-1" are the same? So no "spaces" somewhere?

**Comment by vanessa-azzopardi** [comment]
Thanks for the feedback.

Checked for spaces to make sure the two "-1" are identical but the same keeps happening.  I tried without the householdID just in case but the same happened.

I'll let you know if I figure out what is causing this.

**Comment by ppdewolf** [comment]
You are using 5.1.5 build 3; [the latest release](https://github.com/sdcTools/muargus/releases/tag/5.1.5.3)?

**Comment by vanessa-azzopardi** [comment]
Yes, I'm using 5.1.5 build 3.

![image](https://user-images.githubusercontent.com/75853527/108323850-7462e180-71c7-11eb-8dbb-fed7e00cab3e.png)

**Comment by ppdewolf** [comment]
The next release (5.1.7) will solve the issue of the metadata for "Free with meta" type files. 
As a consequence, also the safe output file will be "Free with meta" (containing variable names on first row).
No release date known yet though, as I am also working on extending the Targeted Record Swapping interface to allow for multiple similarity profiles.

Concerning the "-1" issue: if it still persists, please open a new issue, so we can more easily keep track of things.
