### ISSUE TITLE
Controlled Rounding with Tau-Argus

### ISSUE THREAD

**Issue by MichaelLeviValensin** [sdcTools/UserSupport#163]
Hello
I have a question about controlled rounding in Tau-Argus if you can help me.
When you use the "Controlled Rounding" method for secondary suppressions, you are forced to use a minimum possible base which is equal to the maximum between the minimum frequency threshold and twice the highest Protection level for an unsafe cell.
 Can you explain me why ? And what is the algorithm of the controlled rounding when you have set the base ?

Thank you
---

**Comment by ppdewolf** [comment]
In the manual of tau-argus you can find some more information in section 2.14.
Specifically:
The minimum rounding base is needed to be able to ensure the required safety ranges (induced by the used sensitivity rule).
The algorithm that is used is the one developed by Salazar, see e.g., https://www.researchgate.net/publication/220589932_Controlled_rounding_and_cell_perturbation_Statistical_disclosure_limitation_methods_for_tabular_data
