### ISSUE TITLE
 getInfo finalData problem

### ISSUE THREAD

**Issue by finnbogigunnarsson** [sdcTools/UserSupport#165]
For one year ago I was able to use the command sdcTable::getInfo(t1, type ='finalData' ) 
This year I had to install htmltools to be able to load sdcTable and all was well until getInfo I get this error:
Error in sdcTable::getInfo(t1, type = "finalData") : 
  getInfo:: check argument 'type'!

**Comment by bernhard-da** [comment]
hi @finnbogigunnarsson 

i can only speculate but I guess your `t1` has not yet been protected (using `protectTable()`); thus there are is no slot `finalData` yet; i guess `class(t1)` returns `"sdcProblem"` (and not `"safeObj"` which is a requirement that `type = "finalData"` works)

what does 

```
devtools::session_info()
``` 

say?

**Comment by finnbogigunnarsson** [comment]
It was a fals alarm. I have to run secondary conf before I go til getinfo (I was going to skip it) but I can't aparently



Finnbogi Gunnarsson
Utanríkisverslun | External trade

HAGSTOFA ÍSLANDS | STATISTICS ICELAND
Borgartún 21a - 105 Reykjavík
Beinn sími | Tel: +354 528 1152
Bréfasími | Fax: +354 528 1299

www.hagstofa.is<http://www.hagstofa.is> | www.statice.is<http://www.statice.is>

Fyrirvari | Disclaimer: http://hagstofa.is/um-hagstofuna/fyrirvari/

**Comment by bernhard-da** [comment]
hi @finnbogigunnarsson thx for your reply; if you want to extract the complete table without running `protectTable()` you can use `sdcTable::sdcProb2df(t1)`(in your case)
