### ISSUE TITLE
sdcApp doesn't allow to modify importance for kAnon

### ISSUE THREAD

**Issue by PetraBurdejova** [sdcTools/UserSupport#167]
**SDC tool used:** sdcMicroGUI
**Version used:**  5.6.0 (current one from github)
**Operating system used:** macOS & Win

---
In shiny sdcApp, after I've chosen the option "yes" to modify the importance of key variables for suppression, no option for "Establish k-anonymity" is provided anymore, the button disappears.
Screenshot attached: Done with the testdata provided (chosen 3 keyvars) and done with the current github package version.
![Screenshot 2021-07-15 at 15 18 08](https://user-images.githubusercontent.com/15032050/125800513-0ae8eca5-ba06-4e02-8012-f5147818f25e.png)
Is it a bug, or can it be we're just doing stg wrong? Thank you.

**Comment by bernhard-da** [comment]
hi @PetraBurdejova  thx for reporting this issue; i was able to reproduce and fixed this in https://github.com/sdcTools/sdcMicro/commit/04c02fafe7f4e784b5a260cef8858923dfc9290c

using  
```
remotes::install_github("sdcTools/sdcMicro")
sdcMicro::sdcApp()
``` 
you should be able to work with the updated version;
