### ISSUE TITLE
Other Solvers for sdcTable - ?

### ISSUE THREAD

**Issue by snestler** [sdcTools/UserSupport#169]
Has anyone investigated the idea of using an open-source solver other than GLPK with sdcTable?  The idea being to get better performance when processing large tables.  I'm thinking that CBC might be a better alternative, especially on Linux.  Thank you.

**Comment by bernhard-da** [comment]
hi @snestler thx for your issue; indeed this would be a good idea to investigate but the main problem is that there are no packages providing an api to (e.g cbc) on cran so it would be difficult to keep/put sdcTable on CRAN if it would depend on such solvers; i am aware of https://github.com/dirkschumacher/rcbc and once (hopefully) it makes it way on CRAN, i will consider using it.
