### ISSUE TITLE
Explanatory variables with long values 

### ISSUE THREAD

**Issue by asmukavec** [sdcTools/UserSupport#17]
**SDC tool used:**  tau-argus
**Version used:**  4.1.3
**Operating system used:** Windows
Hi!

Hypercube stops working in case when explanatory variables are too long.

Best regards,
Andreja.

**Comment by ppdewolf** [comment]
Please explain "too long": too many characters in name, too many categories, too many levels, ...?
Can you give a minimal working example, so we can reproduce the error?

**Comment by junoslukan** [comment]
Hello,

Here is a very short example. It contains a list of settlements in four different municipalities and the number of their inhabitants. 

It seems like the **names or labels** of some of the municipalities are too long. Hypercube suppression of _Municipality x Inhabitants_ table fails without a log entry.

[NamesTooLong.asc.txt](https://github.com/sdcTools/UserSupport/files/527459/NamesTooLong.asc.txt)
[NamesTooLong.rda.txt](https://github.com/sdcTools/UserSupport/files/527460/NamesTooLong.rda.txt)

The files' content is included here, too:
**asc**

    01,Ankaran,3235
    02,MiklavzNaDravskemPolju,801
    03,MiklavzNaDravskemPolju,646
    04,MiklavzNaDravskemPolju,4031
    05,MiklavzNaDravskemPolju,1047
    06,SvetiAndrazVSlovenskihGoricah,233
    07,SvetiAndrazVSlovenskihGoricah,75
    08,SvetiAndrazVSlovenskihGoricah,96
    09,SvetiAndrazVSlovenskihGoricah,186
    10,SvetiAndrazVSlovenskihGoricah,83
    11,SvetiAndrazVSlovenskihGoricah,177
    12,SvetiAndrazVSlovenskihGoricah,310
    13,TrnovskaVas,340
    14,TrnovskaVas,184
    15,TrnovskaVas,98
    16,TrnovskaVas,123
    17,TrnovskaVas,69
    18,TrnovskaVas,373
    19,TrnovskaVas,154`

**rda**

    <SEPARATOR> ","
    ID 2
        <RECODEABLE>
        <TOTCODE> "Total"
    Municipality 30 "                            99"
        <RECODEABLE>
        <TOTCODE> "Total"
    Inhabitants 4
        <NUMERIC>

**Comment by ppdewolf** [comment]
Thanks for the MWE. This helps a lot in finding the problem.

It appears that in the Fortran code of the hypercube method, the length of the code-names is limited (in F77 that needs to be defined at compile time) to 8 characters. When code names with more characters are used, it sometimes works, sometimes not (memory problem).

**Comment by ppdewolf** [comment]
Solved with commit 0f86c36 in libtauargus. Arbitrary length code-names should now be possible with hypercube.
