### ISSUE TITLE
Explanatory variables in Specify tables (tau-argus)

### ISSUE THREAD

**Issue by SamelaBA** [sdcTools/UserSupport#184]
*Please specify*  
**SDC tool used:** tau-argus  
**Version used:**  4.2.0
**Operating system used:** Windows

Hello,

My name is Sâmela.
I'm having trouble viewing some variables in the Explanatory variables part. 
I have a lot of explanatory variables in the metadata, and I can't specify some tables because I can't see them.

Best regards,

Sâmela
![image](https://user-images.githubusercontent.com/106394688/170730216-c5b5c653-cba9-4241-846c-a8a7f1185b4d.png)

https://user-images.githubusercontent.com/106394688/170730216-c5b5c653-cba9-4241-846c-a8a7f1185b4d.png

**Comment by ppdewolf** [comment]
Thanks for noticing this. Personally I never use that many explanatory variables, so I hadn't noticed this so far.

I'll have a look at at for the next version.

As a workaround: do you really need all these variables? If not, only specify the variables you need in the .rda file (just specify their location in the datafile). It is not necessary to have all variabels in the data specified in the .rda-file if you don't need them all.
E.g. for the tau_testW.asc file that is included in the release (in the data subdirectory), you could also use the following as a complete .rda-file when you only need the variables Industrycode, Region and Var4:
```
IndustryCode 4  5 99999 
  <RECODEABLE>
  <HIERARCHICAL>
  <HIERLEVELS>  3 1 1 0 0
Region 12  2 99 
  <RECODEABLE>
  <CODELIST> "region.cdl"
  <HIERARCHICAL>
  <HIERCODELIST> "region2.hrc"
  <HIERLEADSTRING> "@"
Var4 48  10 9999999999 
  <NUMERIC>
```

**Comment by ppdewolf** [comment]
In the next release (4.2.5) a scroll bar will be available.
