### ISSUE TITLE
Opening tau-Argus from .NET (6.0).

### ISSUE THREAD

**Issue by kimko567** [sdcTools/UserSupport#187]
tau-argus
4.2.0
Windows 10

I am having an issue launching TauArgus.exe from .NET application. 

When I try to launch TauArgus.exe from cmd.exe that I manually run - everything works fine, the program launches without errors.
However, when I try to launch TauArgus.exe from .NET application, by using Process.Start() (does not matter if I call cmd.exe or TauArgus.exe directly), the program fails to launch with the dialog showing that a Java Exception has occured.

![image](https://user-images.githubusercontent.com/74305155/181186343-ffb75183-fecd-4a48-8b80-5be3a8beba2a.png)

Exception in thread "main" java.lang.UnsatisfiedLinkError: PATH/TauArgus4.2.0b5Windows32bit\TauArgus4.2.0b5\tauhitas.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1946)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1861)
	at java.lang.Runtime.loadLibrary0(Runtime.java:872)
	at java.lang.System.loadLibrary(System.java:1124)
	at tauargus.model.Application.<clinit>(Application.java:70)

ExecuteCommand: ExitCode: 1

tauhitas.dll exits at specified path.

I am having trouble figuring out, what the issue might be. Any ideas?

**Comment by ppdewolf** [comment]
It looks like it cannot find some libraries it needs. Some questions:

How exactly is tauargus started? 
Do you use something like `java -jar PATH_TO_ARGUS\TauArgus.jar` or just `PATH_TO_ARGUS\TauArgus.exe`?

What is the active PATH-environment-variable (i.e., %PATH%) when TauArgus is called from .NET?

**Comment by kimko567** [comment]
Issue solved!

I was starting tauargus by executing PATH_TO_ARGUS\TauArgus.exe.
Looked up some possible reasons for why _java.lang.UnsatisfiedLinkError: Can't find dependent libraries_ can in general occur...

A solution I found that also worked for me was installing Microsoft Visual C++ Redistributable latest version.
