### ISSUE TITLE
sdcMicro::recordSwap, No effect of k_anonymity parameter?

### ISSUE THREAD

**Issue by olangsrud** [sdcTools/UserSupport#191]
**SDC tool used:** sdcMicro,   
**Version used:**    5.7.2  (installed from GitHub)
**Operating system used:**  Windows

---
It seems that the `k_anonymity` parameter in `recordSwap()` in sdcMicro has no effect.
For example, in the example in the package `k_anonymity = 0` and  `k_anonymity = 2` give identical results: 

```
# generate 10000 dummy households
library(data.table)
seed <- 2021
set.seed(seed)
nhid <- 10000
dat <- sdcMicro::createDat(nhid)

# define paramters for swapping
swaprate <- .05 # 5%
similar <- list(c("hsize"))
hier <- c("nuts1", "nuts2")
risk_variables <- c("ageGroup", "national")
hid <- "hid"

# apply record swapping with 
# k_anonymity = 0 and k_anonymity = 2
# and check for identical results
identical(recordSwap(
  data = dat,
  hid = hid,
  hierarchy = hier,
  similar = similar,
  swaprate = swaprate,
  k_anonymity = 0,
  risk_variables = risk_variables,
  carry_along = NULL,
  return_swapped_id = TRUE,
  seed = seed),
  recordSwap(
    data = dat,
    hid = hid,
    hierarchy = hier,
    similar = similar,
    swaprate = swaprate,
    k_anonymity = 2,
    risk_variables = risk_variables,
    carry_along = NULL,
    return_swapped_id = TRUE,
    seed = seed),
)
```

**Comment by olangsrud** [comment]
I see I jumped to the claim of no effect of the parameter too quickly. In the analysis of our own data, `k_anonymity = 0` and `k_anonymity = 1` gave no difference. I then looked at the example in the package and saw that the answer was the same regardless of the value of k_anonymity. But now I see that more risk variables must be added to see differences (as in the tests).

So in a modified version of the example I see differences. But there is still no difference between  `k_anonymity = 0` and `k_anonymity = 1`.

This seems strange and is perhaps not in accordance with the explanation that says:  Setting 'k_anonymity = 0' disables this feature and no risky households are defined.

```
# generate 10000 dummy households
library(data.table)
seed <- 2021
set.seed(seed)
nhid <- 10000
dat <- sdcMicro::createDat(nhid)

# define paramters for swapping
swaprate <- .05 # 5%
similar <- list(c("hsize"))
hier <- c("nuts1", "nuts2")
risk_variables <- c("ageGroup", "national", "hsize")
hid <- "hid"

# apply record swapping with 
# k_anonymity = 0 and k_anonymity = 2
# and check for identical results
identical(recordSwap(
  data = dat,
  hid = hid,
  hierarchy = hier,
  similar = similar,
  swaprate = swaprate,
  k_anonymity = 0,
  risk_variables = risk_variables,
  carry_along = NULL,
  return_swapped_id = TRUE,
  seed = seed),
  recordSwap(
    data = dat,
    hid = hid,
    hierarchy = hier,
    similar = similar,
    swaprate = swaprate,
    k_anonymity = 1,
    risk_variables = risk_variables,
    carry_along = NULL,
    return_swapped_id = TRUE,
    seed = seed),
)
```

**Comment by bernhard-da** [comment]
@olangsrud thx for the report; i jsut tried and I think that using your parameters and setting `k_anonymity = 1`  resulted (given the input data) in no risky-households identified and thus you the procedure yields identical results. if you set `k_anonymity` to anything larger than `1`, you get different results.

**Comment by olangsrud** [comment]
I have read the details more carefully and I see that risky means `counts < k_anonymity` and not `counts <= k_anonymity`. So `k_anonymity = 1`  has no meaning and it is logical that it gives the same answer as `k_anonymity = 0`.   

Sorry, this was a bit embarrassing issue. :)

But one explanation is that my first use of `sdcMicro::recordswap` was inspired by the first example of the function and there `k_anonymity = 1` is used. I think this should be changed.

**Comment by ppdewolf** [comment]
In the vignette (22-07-2022) it says "A record is not at risk if `k_anonymity > counts`." i.e., `counts >= k_anonymity` are at risk. This cannot be true.

Getting in line with the "standard" definition of k-anonymity (can not be distinguished from at least `k-1` other individuals, i.e., >= k is safe) the used definition was changed to `counts < k_anonymity` are at risk. (Around June 2021, IIRC)

@bernhard-da @JohannesGuss So the vignette still has to be adjusted?
