### ISSUE TITLE
Three Dimension Tabular DAta

### ISSUE THREAD

**Issue by ViragMistry** [sdcTools/UserSupport#198]
SDC Tool Used: tau-argus
Version: 4.2.3 Build 1
Operating System used: Windows

I wanted to create the 3 dimension table as under,
![image](https://user-images.githubusercontent.com/49681026/207023196-f10b9c03-3a8a-4e82-a8b9-18ca5c3f1dd6.png)

Please guide me on three dimension table csv file and metadata file structure.

I tried couple of options and getting below mention output,
I am getting my output table but with error 
![image](https://user-images.githubusercontent.com/49681026/207025462-2652474d-cbe9-4e36-878f-01e4a9369485.png)

In case, I am selecting "Compute Incorrect" the below mention output identified, 
![image](https://user-images.githubusercontent.com/49681026/207025161-9eb3c14e-1de2-4626-8e12-fa56849c9948.png)

My CSV file is as under, 
![image](https://user-images.githubusercontent.com/49681026/207025772-5e79fca1-a154-45d1-9f70-8c429b502d9a.png)

---

**Comment by ppdewolf** [comment]
The reason you get a "not additive" error is because there are a lot of subtotals missing in your csv-file and tau-argus expects all (sub)totals, because that is needed for secondary suppression.
(Additionally: note that your csv file contains an error such that the overall total cannot be 70: row 4 should have value 2 according your first picture)

Missing (sub)totals are e.g. `Married;Total;Male` or `Total;More than 30;Male` or `Total;More than 30;Total` or `Total;Total;Male` etc. 

In total there should be 4 * 4 * 3 = 48 cells including all the (sub)totals.

(Note that in you csv file there is also an error such that the overall total cannot be 70 (it is 74): row 4 should have value 2 according your first picture.)

So you would need something like
```
Total;Total;Total;70
Total;Total;Male;48
Total;Total;Female;22
Total;30+;Total;51
Total;30+;Male;35
Total;30+;Female;16
Total;16-30;Total;15
Total;16-30;Male;10
Total;16-30;Female;5
Total;15-;Total;4
Total;15-;Male;3
Total;15-;Female;1
Married;Total;Total;55
Married;Total;Male;38
Married;Total;Female;17
Married;30+;Total;44
Married;30+;Male;30
Married;30+;Female;14
Married;16-30;Total;9
Married;16-30;Male;6
Married;16-30;Female;3
Married;15-;Total;2
Married;15-;Male;2
Married;15-;Female;0
Divorced;Total;Total;11
Divorced;Total;Male;7
Divorced;Total;Female;4
Divorced;30+;Total;5
Divorced;30+;Male;3
Divorced;30+;Female;2
Divorced;16-30;Total;6
Divorced;16-30;Male;4
Divorced;16-30;Female;2
Divorced;15-;Total;0
Divorced;15-;Male;0
Divorced;15-;Female;0
Single;Total;Total;4
Single;Total;Male;3
Single;Total;Female;1
Single;30+;Total;2
Single;30+;Male;2
Single;30+;Female;0
Single;16-30;Total;0
Single;16-30;Male;0
Single;16-30;Female;0
Single;15-;Total;2
Single;15-;Male;1
Single;15-;Female;1
```
Where for the corresponding metadata you could start with somethnig like
```
<SEPARATOR> ";"
"Marital status"
	<RECODABLE>
	<TOTCODE> "Total"
"Hours worked"
	<RECODABLE>
	<TOTCODE> "Total"
"Sex"
	<RECODABLE>
	<TOTCODE> "Total"
freq
	<FREQUENCY>
```

**Comment by ViragMistry** [comment]
Thanks for your guidance. I will try to understand the total concept using this used case. 
Is it possible to make three dimension table using HRC and CLD file?  or Is it only possible in macro data input?

**Comment by ppdewolf** [comment]
`hrc` files are "only" used to define hierarchies in the spanning variables. If there is a hierarchical structure, you should tell tau-argus both with microdata input as well as with tabular (aggregated) input. To that end you can use e.g. a `hrc` file.

In case of tabular input, not specifying there is a hierarchical structure will result in strange tables with "not-additive" errors (the hirarchical structure cannot be recognized by tau-argus based only on the tabular data input): subtotals (like `Nr` in your screenshot) will be seen as a separate code if not specified that the hierarchical structure is `Nr =  1 +  2 +  3`. So in your screenshot the overal total would be equal to the values of `Nr + 1 + 2 + 3 + Os + 4 + 5 + 6 + 7 + Ws = 8 + 9 + 10 + Zd + 11 + 12` which is twice the total of  `Nr + Os + Ws + Zd`.

The `cdl` file is "just" for display purposes. When you have numbers for codes in the input, it specifies how to display a corresponding label (in the screenshot you show: e.g. `4` can be displayed as `Overijssel`)
Both a `hrc` file and a `cdl` file contain definitions _per variable_, so in a 3-dimensional table with two hierarchical spanning variables and one non-hierarchical you would need two `hrc` files.
