### ISSUE TITLE
CPLEX & Xpress License

### ISSUE THREAD

**Issue by ViragMistry** [sdcTools/UserSupport#199]
SDC Tool Used: tau-argus
Version: 4.2.3 Build 1
Operating System used: Windows

I have to work with linear programing solver CPLEX (from ILOG) and Xpress (from FICO). Can you please guide or get the step by step instruction on how to install license files for both (CPLEX and Xpress)to TauArgus?
It would be great if you can share the link to download the software and its license. 

Thank you for your support. 

---

**Comment by ppdewolf** [comment]
CPLEX and XPRESS are commercial solvers. CPLEX is from [IBM](https://www.ibm.com/products/ilog-cplex-optimization-studio) and XPRESS is from [FICO](https://www.fico.com/en/products/optimization).

The xpauth.xpr license file from XPRESS should be located in the directory where tau-argus is installed.

The *.ilm license file from CPLEX could be located anywhere. In the "Help/Options" menu of tau-argus you can specify where to find the license file.

The libraries (*.dll) of both solvers are included in the installation of tau-argus (to ensure the correct version number).
