### ISSUE TITLE
Wrong Apriori file info in report file

### ISSUE THREAD

**Issue by ppdewolf** [sdcTools/UserSupport#20]
**SDC tool used:** tau-argus 
**Version used:**  4.1.3
**Operating system used:** Windows

---

Apply an apriori-file to a table and save the resulting table. The used apriori file will be stated in the report file. When you then recompute the same table and apply another apriori-file and save the resulting table, the first apriori-file info is still written to the report file, i.e., the "old" (no longer valid) apriori-file info is written to the report file. Even though the correct (second) apriori-file is applied to the table.

**Comment by AncoHundepool** [comment]
And what happens if you apply more than one apriori-file?

**Comment by ppdewolf** [comment]
It looks like the temp-file Apriori0.htm is being appended all the time.
When a new table is being constructed and a new apriori is added. Then the first info out of that Apriori0.htm is used in making the report file and is thus "out-dated" info.
Even when restarting tau-argus!

**Comment by ppdewolf** [comment]
Solved by commit db135c9 in tauargus repo.
