### ISSUE TITLE
Implementation of solvers in Tau-ARGUS

### ISSUE THREAD

**Issue by Benjamin-Fuchs** [sdcTools/UserSupport#206]
*Please specify*  
**SDC tool used:** tau-argus
**Version used:** 4.2.3
**Operating system used:** Windows

---

Dear all,

I am uncertain about the exact implementation and usage of solvers. The manual mentions that open as well as commercial solvers can be used. [Meindl and Templ (2012)](https://ec.europa.eu/eurostat/cros/system/files/Analysis%20of%20commercial%20and%20free%20and%20open%20source%20solvers%20for%20linear%20optimization%20problems.pdf) gives an overview on various popular solvers. How exactly can I implement solvers in TAU-ARGUS? Within the Help → Options menu I can choose between Xpress, CPlex and a free solver. For CPlex, I have to select the path where the licence file is. How exactly can Xpress or a free solver be implemented? Is it sufficient just to install such a solver and Tau-ARGUS automatically recognizes it? Do I have to define a path where those solvers can be found within Tau-ARGUS (if yes, where can I set such a path; within Help → Options I can’t find a way to set a path for Xpress or a free solver)? I am unfortunately not familiar with Tau-ARGUS and solvers and I haven’t found an answer to these questions in the manual.

Another question I would like to ask is related to Xpress. The manual mentions on page 7, that Xpress is made available for Tau-ARGUS users. Does it mean, that Tau-ARGUS users are able to get Xpress without any licence costs?

Thank you very much for any help you can offer.

Best regards
Benjamin Fuchs

**Comment by ppdewolf** [comment]
Dear Benjamin,

Cplex and Xpress are commercial solvers, so you'll need to buy a license to be able to use them. 
For Cplex you can specify where your license file is located, as you noticed yourself.
For Xpress, you will need to place the license file (xpauth.xpr) into the directory where tau-argus is installed.
In both cases, the required software libraries are included in the tau-argus release, so you do not have to download any additional software when you want to use those solvers.

For Xpress we have an agreement with Fico (the company that distributes Xpress) that you can get a discount on the license when you can prove to them that you are using Xpress exclusively for tau-argus only.

The free solver is an open source solver (SCIP/Soplex). We have bought a general license for all National Statistical Authorities in the EU so they can freely use the tau-argus software as distributed by us (the version that is included with the release).

In the cell suppression (CSP) and controlled rounding (CRP) procedures, the use of Xpress, Cplex and a free solver are implemented in the source code. So it is not possible to attach any solver you want to tau-argus. If you want to incorporate other "popular solvers" we wil need to adjust the source code of CSP and CRP.

For CTA (Controlled Tabular Adjustment) the following solvers are implemented: Xpress, Cplex, Glpk, Cbc and Symphony.

The other approaches/methods in tau-argus do not need a solver.

I hope this answers most of your questions.

**Comment by Benjamin-Fuchs** [comment]
Dear Peter-Paul,

thank you very much for your quick and detailed answer!

I have one follow-up question: Does your answer regarding free solvers mean that SCIP/Soplex is already implemented in T-ARGUS? If not, is the procedure similar to Xpress?

Best regards 
Benjamin

**Comment by ppdewolf** [comment]
Yes, SCIP/Soplex is already implemented in tau-argus for CSP and CRP. You can use it without additional installations. To do it legally, you should be working at a European NSA :-)

**Comment by Benjamin-Fuchs** [comment]
Thank you again very much!
