### ISSUE TITLE
provide an option to define a working directory

### ISSUE THREAD

**Issue by g3o2** [sdcTools/UserSupport#23]
Navigation within the file dialog windows would be more comfortable if one could define a working directory under the menu `TauArgus options`.

---

**SDC tool used:** tau-argus
**Version used:**  4.1.3-build 1
**Operating system used:** Windows

**Comment by AncoHundepool** [comment]
The idea behind the GUI was that TAU should remember the directory when a file was opened. The next time a file dialogue is opened TAU should go to that directory.
Apparently this is not done at all stages in the code.
I will give it a double check.

**Comment by AncoHundepool** [comment]
We have checked all file dialogues and TAU will now remember the last location.

**Comment by g3o2** [comment]
Will this be done for each dialogue separately? (e.g. last location for `apriori` dialogue, another last location for the `open microdata` dialogue) The reason I ask is because I tend to organise some file types in separate folders.
