### ISSUE TITLE
allow path pasting in file dialog windows

### ISSUE THREAD

**Issue by g3o2** [sdcTools/UserSupport#24]
The file dialog windows used in the application do not allow path pasting, forcing a point & click experience for navigation.

---
**SDC tool used:** tau-argus
**Version used:** 4.1.3-build 1
**Operating system used:** Windows

**Comment by ppdewolf** [comment]
You can copy and paste a path into the `File name:` textbox. If you then click `Open` the file dialog window will jump to that directory.
Isn't this (close to) what you want?

**Comment by ppdewolf** [comment]
Could you reply to my previous comment? Otherwise I will close this issue.

**Comment by ppdewolf** [comment]
No further reply, so will close this issue
