### ISSUE TITLE
sdcMicro removed from CRAN?

### ISSUE THREAD

**Issue by ChrisMannStats** [sdcTools/UserSupport#257]
**SDC tool used:** sdcMicro
**Version used:**  N/A
**Operating system used:** N/A

---

The sdcMicro was apparently removed from CRAN recently (2023-08-10), due to [errors when compiling](https://cran-archive.r-project.org/web/checks/2023/2023-08-10_check_results_sdcMicro.html). Do we know when this is likely to be fixed?

**Comment by matthias-da** [comment]
Thanks for pointing this out. sdcMicro was submitted about three weeks ago, but CRAN maintainers were on vacation.
I resubmitted now again. Should be soon back.
