### ISSUE TITLE
Can’t execute minimum frequency rule and p% rule combined for protecting already existing tables in Tau-Argus

### ISSUE THREAD

**Issue by Benjamin-Fuchs** [sdcTools/UserSupport#263]
SDC Tool: Tau-Argus
Version: 4.2.3 Build 1
Operation system used: Windows 10

Dear all,

I try to write an executable batch file for protecting already existing tables. I was successful in writing a batch that executes a minimum frequency rule and a p% rule separately. But I get error messages whenever I try to write a batch file that contains both rules combined. I started several attempts. The following is currently my most recent one.

My input data file consists of 5 columns. The first two columns include explanatory variables (defined as <RECODABLE> in the rda file), the third column is the response variable (defined as <NUMERIC>) and in column 4 and 5 are the frequencies of the two largest contributors (defined as <MAXSCORE>) to the response variable for each combination of the explanatory variables.

My metadata file in detail:

<SEPARATOR> ";"   // (my input data file is a csv file)
Fahrzeugart		// name of my first explanatory variable, here: type of vehicle
<RECODABLE>
<TOTCODE> "Fahrzeuge insgesamt"
Bundesland	//name of my second explanatory variable, here: German federal states
<RECODABLE>
<TOTCODE> "Deutschland insgesamt"
Fallzahlen	// name of my response variable; here: number of cases
<NUMERIC>
Top1		// name of the variable with the largest contributor for each “type of vehicle/federal state” combination
<MAXSCORE>
Top2	// name of the variable with the second-largest contributor
<MAXSCORE>

	
Within the batch file I specify the table as follows:

<SPECIFYTABLE> "Name of ExpVar1" "Name of ExpVar2" | "Name of ResponseVar" | "" | ""
With empty quotation marks on the third and fourth position I define the response variable as shadow and cost variable (as mentioned in the manual V4.1 on p. 122).

Then I define the safety rule as follows:

<SAFETYRULE> P(10,1)|FREQ(10,5)  

The result is a table full with red cells and I get following messages (the following message is an example for one cell) in the logbook for each cell:

_A real cell with no frequency is strange; In cell (Total,    name of federal state X) freq = 1 has been imputed._

As mentioned before, when implementing only a minimum frequency rule or a p% rule, everything is fine. However, when trying to combine both rules it doesn’t work. I tried different ways (e.g. defining the response variable as frequency which should make no sense when implementing p% rule, …) but I do not get any successful results. I simply have no clue what I do wrong. 

Any help is greatly appreciated.

Best regards
Benjamin

**Comment by ppdewolf** [comment]
Hi Benjamin,

As a first remark: a frequency table in tau-argus is a table where each cell represents the number of _contributors_ to that cell. 

From your description I get the impression that the Fallzahlen is the sum of the contributions of the contributors. I.e., a single contributor could contribute multiple Fahrzeuge to a cell. Even though the table then represents the number of vehicles, it is not a freqency table in the sense of tau-argus tables. It would then still be a magnitude table, where the response variable is integer.

As a consequence, if you specify the Fallzahlen as the response variable, there is no frequency (`<FREQUENCY>`) variable defined. Therefore you will get the message _A real cell with no frequency is strange:..._, as there is no frequency given. 

So you might try to add an additional variable representing the number of contributors to each cell and specify that variable as a `<FREQUENCY>` variable. 

The threshold rule acts on the number of contributors to a cell.

Note that the format for the frequency rule is `FREQ(k,s)` where `k` is the threshold and `s` is the safety range. So your `FREQ(10,5)` means a threshold of 10 contributiors and a safety range of 5%. Not sure if that is what you intend to do.

Not sure if this solves the problem with specifying both a threshold rule and a p%-rule, but it would be worth a try ;-)

Best,
Peter-Paul

**Comment by Benjamin-Fuchs** [comment]
Hi Peter-Paul,

sorry for my late reply. First things first: Thank you very much!

With your explanation I finally understood my mistake. I somehow confound the concepts of frequency and magnitude tables. It seems I have to visit a Statistics and an English 101 course again. 

It was not clear for me that I also have to define the total number of statistical units, who contribute to the magnitude, for each cell. I just defined the number of vehicles for each cell (and also defined this variable as a frequency; another mistake) and added the number of vehicles of the largest and the second-largest statistical unit for each cell. 

Thanks a lot for your explanation!

Best,
Benjamin
