### ISSUE TITLE
Incorrect information message for hypercube linked tables protection

### ISSUE THREAD

**Issue by borisfrenkie** [sdcTools/UserSupport#267]
*Please specify*  
**SDC tool used:** tau-argus
**Version used:** 4.2.4 Build 2
**Operating system used:** Windows

---

Hi,

there is just a minor cosmetic issue with the information message on linked tables protection with the use of hypercube method. 

When protection is undertaken, a modal shows the same number of secondary suppressions for both tables, even if the numbers are different:

![fig1](https://github.com/sdcTools/UserSupport/assets/22882713/a2f4d1d1-3dfc-4d42-b200-60f8a36f246f)

![fig2](https://github.com/sdcTools/UserSupport/assets/22882713/3767fa6e-3637-4c7a-85b1-4832788ce80c)

![fig3](https://github.com/sdcTools/UserSupport/assets/22882713/be386762-a8ab-4663-8a28-73b92cbe2c56)

Best,

Boris

**Comment by ppdewolf** [comment]
Will be fixed in next release (4.2.5)
