### ISSUE TITLE
Decimal in zero unsafe tau-Argus 4.1.3

### ISSUE THREAD

**Issue by Lars-ErikAlmberg** [sdcTools/UserSupport#28]
SDC tool used: tau-argus
Version used: 4.1.3
Operating system used: Windows

Specify tables. If you choose Zero unsafe tau-Argus include a decimal in the range. Suddenly 10 (for example) becomes 10.0 and then you can´t build a table. If you write a batch file the parameter will be 10.0 and you can´t Open batch process without error.
To be more specified this don´t happen the first time you build the table. But if you reverse with arrow up to try some other settings the 10 becomes 10.0 and you can´t build the table with arrow down.
I include an example with synthetic micro data. 

Lars-Erik Almberg Statistics Sweden
[Decimals zero unsafe.zip](https://github.com/sdcTools/UserSupport/files/592069/Decimals.zero.unsafe.zip)

**Comment by ppdewolf** [comment]
Thanks for the example. 
In the version I'm working on right now, this seems to be fixed (I can build the table in both cases, with and without decimal). Apparently this is solved by taking care of issue #4.
E.g. the following batch-file now works with me: 
[test.arb.txt](https://github.com/sdcTools/UserSupport/files/594814/test.arb.txt)
I'll close this issue for the time being. I intend to publish a next release in December at the latest.

**Comment by Lars-ErikAlmberg** [comment]
Thanks for the help!
