### ISSUE TITLE
Primary suppressed datasets with decimals tau-Argus 4.1.3

### ISSUE THREAD

**Issue by Lars-ErikAlmberg** [sdcTools/UserSupport#29]
SDC tool used: tau-argus
Version used: 4.1.3
Operating system used: Windows

We had problems with decimals when reloading a table back into tau-Argus for linked secondary suppression. Tau-Argus said the tables (that it has created) were non additative. I removed the decimals and then it was no problem.
I include two synthetic micro datasets. _dec is with one decimal. _prim is already primary suppressed datasets that is saved in tau-Argus. I can´t get the _dec-version to work.
[Decimals in tabledata.zip](https://github.com/sdcTools/UserSupport/files/592290/Decimals.in.tabledata.zip)

Lars-Erik Almberg Statistics Sweden

**Comment by ppdewolf** [comment]
Reading a single table created by tau-argus (with decimals) gives the message "non-additive" but without any information on cells that would be non-additive. As there are indeed no non-additive cells.
I'll have to look into this.

**Comment by AncoHundepool** [comment]
It looks as if the tau engine find some non-additivities, but this is probably to to some numerical precision problems. And subsequently the UI cannot find them so the overview is empty.
This will take some more time, sorry.
For the time being reduce the precision (e.g. no decimals() as in the end you are only interested in the suppression pattern and not the cell values.

**Comment by ppdewolf** [comment]
Am I correct in assuming that you construct your table from microata input, then save it yourself in "intermediate" format and try to reread the table into TauArgus?

**Comment by Lars-ErikAlmberg** [comment]
Yes, that is the way we do it.

**Comment by ppdewolf** [comment]
Solved. Will be part of next release.
