### ISSUE TITLE
Results for k-anonymity in sdcMicro vs mu-ARGUS

### ISSUE THREAD

**Issue by inesrsa** [sdcTools/UserSupport#293]
*Please specify*  
**SDC tool used:** sdcMicro
**Version used:**  5.7.8
**Operating system used:** Windows

---

Hi,

I need to count the number of observations in a dataset that violate k-anonymity.

As an example, I´m using the public use demo dataset from mu-Argus and considering REGION, SEX and AGE as key-variables.

When I compare the results obtained by using mu-ARGUS with those obtained from sdcMicro, they are the same for k=2, but differ for k>2. 
 
For k = 3, for instance, in mu-ARGUS I´m specifying the combination/threshold as following:

![mu-ARGUS_k-anonymity_1](https://github.com/user-attachments/assets/49843e1d-d9fc-495d-acc8-1916fe7be847)

and getting the following results (**3058 observations** violating 3-anonymity when combining the 3 variables):

![mu-ARGUS_k-anonymity](https://github.com/user-attachments/assets/4453f448-abf0-4b37-be6e-8e5464d8bb3e)

With sdcMicro, either by using the ```freqCalc``` or the ```kAnon_violations``` functions, the result is that **3452 observations** are violating k-anonymity for k=3.

```{r}
library(sdcMicro)
data(free1)
kv <- c("REGION", "SEX", "AGE")
fr1 <- freqCalc(free1, keyVars = kv, w = NULL)
fr1
```
```{r}
sdc1 <- createSdcObj(
  free1,
  kv,
  weightVar = "WEIGHT"
)
kAnon_violations(sdc1, weighted = FALSE, k = 3)
```

Why are the results different in this case?

I´d greatly appreciate any assistance or clarification on this.
Thank you!
Ines

**Comment by bernhard-da** [comment]
@inesrsa hi, I think this is just due to a different way on how violations are defined in `sdcMicro` and `mu-argus`.

Let me try to show you. I am using the example data because there are no `NAs` or weights involved and therefore fk equals Fk;

```r
library(sdcMicro)
library(data.table)
data(free1)
free1 <- setDT(as.data.frame(free1))
kv <- c("REGION", "SEX", "AGE")
free1 <- free1[, c(kv), with = FALSE]

# Aggregate by keyvars
setkeyv(free1, kv)
agg <- free1[, .(Fk = .N, fk = .N), by = key(free1)]; agg

# we can see that there are 3213 different combinations (keys) given the
# 3 keyvars, but for example the key combination 
# REGION=1 | SEX = 1 | AGE = 17 occurs 4 times in the data
Key: <REGION, SEX, AGE>
      REGION   SEX   AGE    Fk    fk
       <num> <num> <num> <int> <int>
   1:      1     1    17     4     4
   2:      1     1    20     1     1
   3:      1     1    31     3     3
   4:      1     1    32     1     1
   5:      1     1    34     1     1
  ---                               
3209:    182     1    32     1     1
3210:    182     1    35     1     1
3211:    182     1    68     1     1
3212:    182     2    34     1     1
3213:    182     2    57     1     1

# When we compute violations (eg. violating 3-anonymity) it seems that in mu-argus the number of _keys_ violating k_anon are shown
sum(agg$Fk < 3) # 3058

# while in sdcMicro, we actually count the number of persons/units that violate k-anon
agg[Fk < 3, sum(Fk)] # 3452
```

**Comment by inesrsa** [comment]
@bernhard-da Thank you so much for helping me clarify this!

**Comment by ppdewolf** [comment]
I don't understand. Why is a key that occurs 4 times in the data, violating 3-anonymity?

Note there is a difference in defining k-anonymity in mu-argus versus sdcMicro. Specifying k in mu-argus and using the counts would be the same as k+1 anonymity in sdcMicro. 

I'm currently on holiday, so I will be able to reply more thoroughly when I'm back.

**Comment by inesrsa** [comment]
Thanks @ppdewolf, it can't get clearer than that 😀
