### ISSUE TITLE
Log file in batch mode tau-Argus 4.1.3

### ISSUE THREAD

**Issue by Lars-ErikAlmberg** [sdcTools/UserSupport#30]
SDC tool used: tau-argus
Version used: 4.1.3
Operating system used: Windows

In batch mode tau-Argus don´t produce a log file into the specified folder.
We specify the log file like this:
<LOGBOOK>        "C:\...\SAStmp\tab_1.LOG"

Lars-Erik Almberg Statistics Sweden

**Comment by Lars-ErikAlmberg** [comment]
Thanks! Just for clarification it didn´t work when we specified it in the arb-file like 
<LOGBOOK>        "C:...\SAStmp\tab_1.LOG"

**Comment by ppdewolf** [comment]
Just to be sure: in my Windows command prompt I cannot use "cd C:...\foo". It will complain with "The system cannot find the path specified". I think you explicitly need a slash after "C:".

**Comment by Lars-ErikAlmberg** [comment]
Thanks, yes I missed that in my comments above. But in the code we tested we had it right. Can you specify a log file in the arb-file in batch mode and get it to work?

**Comment by AncoHundepool** [comment]
You can indeed specify the logfile in the ARB. For the time being just omit the quotes round the file name. 
That is a problem in the current version.
But that should be possible again in the next release.

**Comment by Lars-ErikAlmberg** [comment]
Thank you very much!
