### ISSUE TITLE
Linked sec suppress in batch mode tau-Argus 4.1.3

### ISSUE THREAD

**Issue by Lars-ErikAlmberg** [sdcTools/UserSupport#31]
SDC tool used: tau-argus
Version used: 4.1.3
Operating system used: Windows

We can´t get linked secondary suppression in batch mode to work. The syntax in the arb-file that works with 3.5.0 doesn´t work here (see arb-file in zip file).

Lars-Erik Almberg, Statistics Sweden

Synthetic data:

[Linked sec suppression in batch mode.zip](https://github.com/sdcTools/UserSupport/files/594075/Linked.sec.suppression.in.batch.mode.zip)

**Comment by ppdewolf** [comment]
I'll have a closer look, but there are two things you might try:
1) In your example H_1A_prim.tab on line 8 the sum of the two largest values is greater than the cell-value. This should not be possible.
2) The correct format now is MOD(0). The tablenumber 0 will tell tau-argus that a linked procedure should be used.

**Comment by Lars-ErikAlmberg** [comment]
1) Do you mean the row with H4931?
2) Thank you very much! It works as it should with MOD(0)   :)

**Comment by ppdewolf** [comment]
1) That's the row I meant ;-)
2) Nice. We'll add some more information on this in future manual
