### ISSUE TITLE
Apriori file with code 'Total'

### ISSUE THREAD

**Issue by Lars-ErikAlmberg** [sdcTools/UserSupport#35]
SDC tool used: tau-argus
Version used: 4.1.3
Operating system used: Windows

When we do consent control at Statistics Sweden we first run SAS2Argus (tau-Argus) for primary suppression. Then we do consent control and write an apriori file with the cells that should be set to safe. When we run  SAS2Argus the second time to do secondary suppression we use the tabulated result from the first run because tau-Argus don't understand the code 'Total' in the apriori file if we use the micro data option.

This is a good solution exept in the case where there are negative contributions to a cell. In this case it might happen that top1 (in absolut value) is larger than the sum of the cell and then tau-Argus will not accept the table. This can be solved by taking the absolut value on every contribution in micro data and do some manually inspection of the result.

But the best way to do this would be to use microdata in the second run combined with the apriori file. I include some made-up data where it is possible to set the 'Total' cell to safe with the apriori function if you load it as table data but it´s not possible to do this if you load it as micro data. This is no bug I guess, it was the same with 3.5.0, but maybe this colud implemented in newer versions of tau-Argus?

Lars-Erik Almberg, Statistics Sweden

[Apriori.zip](https://github.com/sdcTools/UserSupport/files/631063/Apriori.zip)

**Comment by g3o2** [comment]
Instead of `Total` simple leave the cell empty (no space) in the `.hst` file: e.g. `, c, 100` instead of `Total, c, 1` or e.g. for two dimensions `"K",, c, 1` or even `,, c, 1`

I agree it is not intuitive but it works.

**Comment by Lars-ErikAlmberg** [comment]
Thanks! It works as it should with empty space instead of Total :)

**Comment by ppdewolf** [comment]
This is indeed the way it was implemented (empty as "total"-code) in the a-priori file. Not sure exactly the reason behind.

We'll have to add more info on this in the manual.

For now I close this issue.

**Comment by AncoHundepool** [comment]
I think that your code for total should work in an apriori file.
But only if you have specified this total code in the metadata (RDA). Note: case sensitive!

**Comment by Lars-ErikAlmberg** [comment]
Ok, thank you!
