### ISSUE TITLE
Cost and shadow with micro data tau-Argus 4.1.3

### ISSUE THREAD

**Issue by Lars-ErikAlmberg** [sdcTools/UserSupport#39]
SDC tool used: tau-argus
Version used: 4.1.3
Operating system used: Windows

With tau-Argus 3.5.0 you could specify a cost and a shadow variable when creating a table from micro data. But with 4.1.3 you get an error if you have <NUMERIC> <SHADOW> or <NUMERIC> <COST> in the meta data file. Is this a bug? In the manual this option is indeed only for tabulated data.

Lars-Erik Almberg Staistics Sweden

**Comment by ppdewolf** [comment]
Also in version 4.1.3 you can still use cost and shadow variables: you have to specify them when you define the table in the "Specify Tables" dialog. Any of the "response" variables in your microdata can be used as shadow or cost variable. It is not specified in the metadata in combination with microdata input. As far as I remember that was also not specified in the metadata in version 3.5.0 and would result in an error message in version 3.5.0 as well.

Or are you talking about constructing a table from microdata in an arb-file (batch-file)?

**Comment by AncoHundepool** [comment]
Maybe the confusion is  that for tabular input you have to specify in the RDA file that a variable is the shadow variable of that table, while when computing a table from microdata any numeric/response variable can be selected to serve as shadow. That is why <shadow> is not meaningful as a parameter in the RDA for microdata and hence it is not allowed.

**Comment by Lars-ErikAlmberg** [comment]
Thanks for the answers. We have to change SAS2Argus so that it only specify the cost and the shadow variables in the arb-file. I tried that and then it works as it should :)
