### ISSUE TITLE
2016003 Zero unsafe" wordt niet meegenomen

### ISSUE THREAD

**Issue by rvdlaar8** [sdcTools/UserSupport#4]
Version used: 4.3.1
Windows
"Zero unsafe" not used!

**Comment by ppdewolf** [comment]
Is tested with Integer.parsInt() but is allowed to be double (defaults to 0.0). 
Now tested with Double.parsDouble(). 

Fixed

**Comment by ppdewolf** [comment]
Does not work correctly in using this range in the calculation of the table

**Comment by ppdewolf** [comment]
Is fixed with commit 5963ea8 in tauargus repo and f5eb198 in libtauargus repo
