### ISSUE TITLE
Problems with weight

### ISSUE THREAD

**Issue by Lars-ErikAlmberg** [sdcTools/UserSupport#40]
SDC tool used: tau-argus
Version used: 4.1.4
Operating system used: Windows

Tau-Argus crashes when you specify "Apply weights" and then "Compute tables".  This worked with 4.1.3. 

[Weight.zip](https://github.com/sdcTools/UserSupport/files/722937/Weight.zip)

Lars-Erik Almberg Staistics Sweden

**Comment by ppdewolf** [comment]
I have uploaded a test release, trying to correct for this bug. Could you try? Just replace the TauArgusJava.dll in the directory where tau-argus is installed, with the new one.
