### ISSUE TITLE
save tables - variables names not written to output file

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#42]
**SDC tool used:** Tau-Argus
**Version used:**  4.1.4
**Operating system used:** Windows

---

When saving a protected table (code-value format), the variable names are not written to the output-file even if `Variable names on first row` has been selected. The same happens, if I specify e.g.

`<WRITETABLE> (1, 3, AS+SE-FL+, "somefile.txt")`

in a batch-input file.

**Comment by ppdewolf** [comment]
Dealing with selected options was not implemented correctly. Now corrected. Will be fixed in next release.
