### ISSUE TITLE
dropped options when writing a batch-file

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#43]
**SDC tool used:** Tau-Argus
**Version used:**  4.1.4
**Operating system used:** Windows

---

### problem

when creating a batch-file, some options (e.g `Apply weights` and `Missing==safe`) in `Specify` ->`Tables` seem to be dropped when the batch file is written.

###  steps to reproduce
- use the following [microdata](https://gist.githubusercontent.com/bernhard-da/d17ae53a242f8f9eaa5510df22b6ba3f/raw/9e92ef48713886a9a1be435d98f1abe1e3119a77/microdata.asc)
- use the following [metadata file](https://gist.githubusercontent.com/bernhard-da/c405493f602029e16a519fba23e1ab2f/raw/c009f9df059547bab9d0603ed4c98675bf352f32/metadata.rda)
- `File` -> `Open Microdata` -> select the above data and metadata files
- `Specify` -> `Tables`
- create first table
   - select `region` and  `gender` as explanatory variables
   - select `num1` as response variable
   - use a minimum frequency `FREQ(5,20)` and DONOTcheck either `Apply weights` or`Missing==safe`
   - add this as the first table
- create second table table
   - use same settings as above but DO check `Apply weights` and`Missing==safe`
   - add this as the secondtable

In the overview table at the bottom, the two table seem to be different as they have different values in the column `Shadow & cost var`

- press `compute tables`
- Use `Output` -> `Write Batch File` to create a Batch File. This file now has the following content (showing only the relevant sections):

```
<OPENMICRODATA>    "microdata.asc"
<OPENMETADATA>     "metadata.rda"
<SPECIFYTABLE>     "region""gender"|"num1"||
<SAFETYRULE>       FREQ(5,20)
<SPECIFYTABLE>     "region""gender"|"num1"||
<SAFETYRULE>       FREQ(5,20)
<READMICRODATA>
<GOINTERACTIVE>
```
the two tables do not differ in any way.

**Comment by AncoHundepool** [comment]
The weight and Missing=Safe parameters have been added.
Also the WRITETABLE command is now included  in the batch-file
