### ISSUE TITLE
Batchfile: Keyword not allowed in this position

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#44]
**SDC tool used:** Tau-Argus
**Version used:**  4.1.4
**Operating system used:** Windows

---

Trying to use [**this simple batchfile**](https://gist.githubusercontent.com/bernhard-da/ec41e6104677af76eac5a3f0ad4ce301/raw/a0bdaa7bb0972b2a620fd42e9861d0400cf214fa/batch.arb), I get the following error:

```
Error in batch file
Command: <READTABLE>
This keyword (<READTABLE>) is not allowed in this position
```

The input data are correct because I can upload (and protect) them successfully using `File` -> `Open Table`.

**Comment by ppdewolf** [comment]
You didn't specify any safetyrule to use. You need that before you can read the table.
E.g., use <SAFETYRULE> MAN(0) to use given status and given safetyranges

**Comment by bernhard-da** [comment]
Thx for the answer which makes perfect sense. I would suggest however to add this line to the example batch-file for tabular input shown in the manual on page 125 because in my opinion the currently shown batch-file is not valid.

**Comment by ppdewolf** [comment]
Good point. We're actually thinking about including automatically assuming given status and safetyranges when <SAFETYRANGE> is missing (and indeed available in the data).
But changing the manual is a good point as well :-)
For now I'll close this issue.
