### ISSUE TITLE
"Table is not additive;" (whereas it is)

### ISSUE THREAD

**Issue by the-knife** [sdcTools/UserSupport#46]
**SDC tool used:**  tau-argus
**Version used:**  4.1.4
**Operating system used:** Windows 7

---
Hello,

Tau-Argus is wrongly stating that a table (*.tab) is not additive, while it obviously is.

Apparently, the problem occurs when the response variable has decimals (the same data converted to integers works).

Furthermore, TA is unable to point out which cells cause the problem. The information text is empty.

There follows a simple example that should reproduce the bug (I attached the files as well if you need to test : [additive_tables.zip](https://github.com/sdcTools/UserSupport/files/799788/additive_tables.zip)).
I checked this is actually additive. Furthermore, version 3.5.0 does not complain about non-additivity.

**decimals1.tab**
```
A1;B1;70911.7;40
A1;B2;64512.5;447
A1;TOTAL;135424.2;451
A2;B1;2856.1;5
A2;B2;2276;65
A2;TOTAL;5132.1;65
TOTAL;B1;73767.8;40
TOTAL;B2;66788.5;447
TOTAL;TOTAL;140556.3;451
```
**decimals1.rda**
```
<SEPARATOR> ;
<SAFE> S
<UNSAFE> U
<PROTECT> P
V1
  <RECODEABLE>
  <TOTCODE> TOTAL
V2
  <RECODEABLE>
  <TOTCODE> TOTAL
RESP
  <NUMERIC>
  <DECIMALS> 1
TOP1
  <MAXSCORE>
```

This version with integer values for response variable works both on 3.5.0 and open source version.

**decimals0.tab**
```
A1;B1;70912;40
A1;B2;64513;447
A1;TOTAL;135425;451
A2;B1;2856;5
A2;B2;2276;65
A2;TOTAL;5132;65
TOTAL;B1;73768;40
TOTAL;B2;66789;447
TOTAL;TOTAL;140557;451
```
**decimals0.rda**
```
<SEPARATOR> ;
<SAFE> S
<UNSAFE> U
<PROTECT> P
V1
  <RECODEABLE>
  <TOTCODE> TOTAL
V2
  <RECODEABLE>
  <TOTCODE> TOTAL
RESP
  <NUMERIC>
TOP1
  <MAXSCORE>
```

Can you confirm this is a bug ? Let me know if you need more information.

Regards,

Pierre-Yves

**Comment by ppdewolf** [comment]
Not sure what happens here. I've installed the 4.1.4 version as given on the release pages. Running your example I do not get the non-additivity error: it nicely shows the table.
Could you reinstall 4.1.4 with the version as given on [the latest release page](https://github.com/sdcTools/tauargus/releases/tag/v4.1.4) and check again?

**Comment by the-knife** [comment]
Still not additive after I reinstalled 4.1.4.
Same with 4.1.3.
**But it works with 4.1.1b1 !**

**Comment by julienlemasson** [comment]
Hi, 
I tried this example too. On my computer, the **decimals1.tab** (is this one that you tried -not the decimals0)?) does not work , it is said that "table is not additive ; something wrong" and then an overview :
Overview of the non-additive cells
--------------------------------------------------
Table-file: Z:\exemple TA\test github\decimals1.tab
Meta-file:  Z:\exemple TA\test github\decimals1.rda
Date: Mon Feb 27 14:06:00 CET 2017
--------------------------------------------------
JL

**Comment by julienlemasson** [comment]
Hi,
I tried this example too. On my computer, the decimals1.tab (is this one that you tried -not the decimals0)?) does not work , it is said that "table is not additive ; something wrong" and then an overview :
Overview of the non-additive cells
Table-file: Z:\exemple TA\test github\decimals1.tab
Meta-file: Z:\exemple TA\test github\decimals1.rda
Date: Mon Feb 27 14:06:00 CET 2017

JL

**Comment by julienlemasson** [comment]
In fact, it works with 4.1.1 and 4.1.2, but not with 4.1.3/4.1.4.

**Comment by ppdewolf** [comment]
Probably has to do with compiling on 64 bit machine and running on 32 bit JVM. Working on it.

**Comment by julienlemasson** [comment]
My machine is actually 64 bit. I did not notice that Tau-Argus 4.1 was on 32 bit. It may explain some others bugs I wanted (someday ...) to talk about here (some display issue : when i tabulate tables, sometimes nothing appears on the software).

**Comment by ppdewolf** [comment]
At [test release TauArgusJava](https://github.com/sdcTools/libtauargus/releases/download/testIssue29/TauArgusJava.dll) you find a pre-release of an adjusted TauArgusJava.dll. Replace the one in the directory where tau-argus is installed by this one. No guarantee that this simple replacement will work though, because there may be some dependency on the java-code of the interface. In that case you will have to wait for the next official release.

**Comment by julienlemasson** [comment]
It works (with example "decimals1") ! I 'll try to see if that correct other issue that i talked about.
Thx a lot.

**Comment by the-knife** [comment]
Awesome! Thank you.
