### ISSUE TITLE
2016004 In een tab-file worden "lege" cellen gevuld met een 1

### ISSUE THREAD

**Issue by rvdlaar8** [sdcTools/UserSupport#5]
Version used: 4.3.1
## Windows

C,6,S
C1,,S
C2,,S
C3,4,S
C4,2,U
C5,,S
Geeft bij inlezen foutmelding dat niet additief is (6 <> 1 + 1 + 4 + 2 + 1 = 9)

TWEE DEELPROBLEMEN:
2016004_A In een tab-file verbieden dat een <FREQUENCY> variabele leeg (of nul) is met een status ongelijk aan E
2016004_B Vreemde protection levels bij unsafe (U) cellen als <FREQUENCY> variabele (ook) als response variabele wordt gebruikt

**Comment by AncoHundepool** [comment]
Het is natuurlijk helemaal onzin/zot dat een lege cel een waarde 1 krijgt als er geen respons in ingevuld.

Verder kunnen we of verbieden dat C1,,S wordt opgegeven san wel onderzoeken of we er een non-structural empty van kunnen maken.

**Comment by ppdewolf** [comment]
Subproblem B 
The table input used rda that defined per row:
code, frequency, status
So no response variable. Should we allow for only frequency variable without response variable?

**Comment by AncoHundepool** [comment]
In the old TAU is was also possible to have only a frequency and no real response variable. Typically a frequency table. So we will bring back this option in the new TAU.

Furthermore  we will accept the line 
C1,,S
But we will treat is as a normal empty cell. 
However
C1,,U 
will still lead to an error

**Comment by ppdewolf** [comment]
fixed in commit #8349d3e of tauargus repository
