### ISSUE TITLE
Do not deselect the cell after setting to protected/unsafe or setting its cost

### ISSUE THREAD

**Issue by junoslukan** [sdcTools/UserSupport#50]
SDC tool used: Tau-Argus
Version used:  4.1.4
Operating system used: Windows
---
When a cell is selected and then "Set to protected" or unsafe, it is **de**selected. To set another cell to protected or safe, a user must _click on it and then go back_ to "Set to protected" (or unsafe). Going back and forth with a mouse pointer is unavoidable in this scenario.

In earlier versions of Tau-Argus (e.g. 3.5.0), a user could set one cell to protected or unsafe, which _stayed selected_, and then move to another by using **the arrow buttons of the keyboard**, without resorting to clicking. The mouse pointer could then rest within the "Change status" panel, which made for quicker operations.

Is there any possibility of bringing this functionality back?

**Comment by ppdewolf** [comment]
Will be available from version 4.1.7
