### ISSUE TITLE
High dimensional table gives strange error message

### ISSUE THREAD

**Issue by ppdewolf** [sdcTools/UserSupport#52]
**SDC tool used:** tau-argus
**Version used:**  4.1.4
**Operating system used:** Windows

---

When trying to use modular on a non-hierarchical table with more than 4 dimensions, gives strange error message ("complete table has to be skipped?").

**Comment by AncoHundepool** [comment]
Anyhow this should be forbidden as Modular is restricted to max 4 dimensions. Should be checked.

**Comment by ppdewolf** [comment]
Since version 4.1.6b2 a check is done on the number of dimensions. Over 4 dimensions is not allowed. A "meaningful" error-message is thrown.
