### ISSUE TITLE
"Something wrong" after nonadditive table in arb file

### ISSUE THREAD

**Issue by junoslukan** [sdcTools/UserSupport#53]
**SDC tool used:** Tau-Argus
**Version used: 4.1.5 and 4.1.4**  
**Operating system used:** Windows

---
To recreate this problem, the first step is to try to open a batch file which would want to read a table that is not additive. This throws an error "Error in batch file, Command: < READTABLE >, Table is not additive". Next, try to open another table that **is** additive. When specifying tables another **Message** pops up: **"0; something wrong"**. 

This message insists for every table until either: a) Tau-Argus is restarted or b) another batch file is opened, which runs without any errors.

---

A thought about the underlying problem: Tau-Argus seems to "hold" the last .arb file that was opened. A similar symptom is that editing and saving an "open" .arb file takes a lot of time. By "open" I mean that Tau-Argus tried to run it, but ran into trouble, but no other operation was done by Tau-Argus.

---

Sample data files:

An additive frequency table: 
[tabela_4.tab.txt](https://github.com/sdcTools/UserSupport/files/979044/tabela_4.tab.txt)

The same table with a cell changed, so that it is not additive any more:
[tabela_4nonAd.tab.txt](https://github.com/sdcTools/UserSupport/files/979045/tabela_4nonAd.tab.txt)

The accompanying .rda file:
[tabela_4.rda.txt](https://github.com/sdcTools/UserSupport/files/979040/tabela_4.rda.txt)

The .arb file to try to suppress the nonadditive table:
[tabela_4nonAd.arb.txt](https://github.com/sdcTools/UserSupport/files/979047/tabela_4nonAd.arb.txt)

**Comment by AncoHundepool** [comment]
Dear Friend,

I think that

**Comment by AncoHundepool** [comment]
A non-additive table is not accepted in the current batch version. You will now get a decent message in the log-file.
However a new issue should be opened to handle the non-additivity as in the GUI-version

**Comment by ppdewolf** [comment]
According to the manual it should be possible to deal with non-additive tables ("set only parameter of `<READTABLE>` to 1, default is 0"). However, that setting is not used when actually reading the table(s)...
