### ISSUE TITLE
Select solver in tauArgus batch file

### ISSUE THREAD

**Issue by alexkowa** [sdcTools/UserSupport#55]
**SDC tool used:** tauArgus
At the moment tauArgus does not incoporate the possibility to select the used solver in the batch file.
This would be a great enhancement when called from other tools.

**Comment by AncoHundepool** [comment]
Oeps you found a little typo in the code. Sorry.
But selecting a solver it is an option in the batch file. See page 124 of the manual.
For the time being, select a solver via the GUI and protect one table.  
Then TAU will remember the selected solver.

**Comment by bernhard-da** [comment]
Hi. The real enhancement would be, if it could be avoided to manually start mu-argus in graphical mode to select the solver. This would allow for a complete headless operation. 

Adding a new (optional) keyword (which should be ignored if the `FREE` solver has been specified) to the batch-file could solve this, e.g:
```<SOLVERLICENSE> "/path/to/my/licensefile"```

**Comment by AncoHundepool** [comment]
A good point. But I prefer to add a second optional parameter to the <SOLVER> command.
Like 
<SOLVER>  CPLEX, licensefile
Note that for XPress the name of the licence file cannot be changed and the location is mandatory the TAU directory.

**Comment by AncoHundepool** [comment]
Solved

**Comment by bernhard-da** [comment]
thx @AncoHundepool for implementing this. could you eventually also update the manual on how to use this feature?
