### ISSUE TITLE
SAS2ARGUS: provide example inputs 

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#56]
**SDC tool used:** SAS2ARGUS
---

It would be very helpful if the example-files used in the document **"User and system description  of SAS2ARGUS"** (e.g. `Example1.csv`, `Example1.rda`) could be uploaded to this repo so that users can reproduce the examples in the manual.

**Comment by ppdewolf** [comment]
Demo uploaded to SAS2Argus repo.
