### ISSUE TITLE
User temp-dir (if specified) for all outputs when relative paths are used in a batch-file

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#57]
**SDC tool used:** tau-argus
**Version used:**  4.1.5
**Operating system used:** Windows

---

When a relative path is given in a `<WRITETABLE>`-command in a batch-file such as
```
<WRITETABLE>  (2,4,SE+,"myoutput.tab")
```
the resulting table(s) are written to `Taupath` which - according to the manual - is the name of the directory where argus is installed. In the manual in section 5.7 it is also described how to generally use `param1`, `param2` and `param3` when calling argus from bash. 

It would be very helpful (for the automated testing of tau-argus via commandline from **R**) if all output (including output tables) is written in the directory specified by `param3` (the temp-directory to be used) in case relative-paths are used in the batch input file and the temp-directory has been overwritten via `param3`. This would mean calling a batch-file containing the example line from above using

```
c:/Tau/TauArgus.exe /path/to/mybatch.arb /path/to/mylogfile /path/to/mytemp 
```
would save `myoutput.tab` in `/path/to/mytemp`.

If implemented, the batch-files used for the automated testing may contain relative file paths which would very much simplifiy the testing procedure and the creation of batch files for testing purposes.

**Comment by ppdewolf** [comment]
The `TEMP`-directory is used to save all kind of intermediary files used in the process of protecting a table. I don't think it would be a good idea to use the `TEMP`-directory to store the output files as well. 

Would an additional command in the batch-file that specifies the output-directory for any "real" output help you? Or would a `param4` be helpful?

By the way: does the `param3` actually work in your situation?

**Comment by bernhard-da** [comment]
hi @ppdewolf , thx for replying.

1) yes, param3 does work in the sense that all the temporary output (the JJfiles,..) are written to this directory. It does not work however for final output specified in `<WRITETABLE>`. 

It would however be nice if one could omit some of the params, by eg. using a syntax like 

```c:/path/to/argus.exe param1=.. param3=...```

2) Indeed it might be easier to implement a `param4=` solution to fix this issue.  If we could specify `param4=/path/to/some_dir` and set a relative path in the `WRITETABLE` section and the output tables would be written to `/path/to/some_dir` that would be perfectly fine for the testing purposes.

**Comment by AncoHundepool** [comment]
Hi Bernard,

Adding this output dir for batch jobs is not too much. However why should this information only be used for output files and not for input files? Maybe we should extend this idea.

Since we are now extending the number of parameters for running TAU in batch, indeed named parameters can be useful.
I will see what I can do.

**Comment by bernhard-da** [comment]
hi @AncoHundepool, thx for working on this!

To have also parameters for the inputs would be even better. Also, it might be useful to have "meaningful" names for the parameters as param1 to paramN are probably not really intutive :)

**Comment by AncoHundepool** [comment]
Hi @bernhard-da 
I was thinking of a more general concept of something like a current data directory.
Tau should prefix this to each data file that contains no path-information. 
The GUI should set this each time the File-Open-Box is invoked.
The Batch-version could us this as a prefix each time a file reference is made without the path-information.

And in a later stage of course I would opt for more meaningful names that param1 param2 etc.

**Comment by AncoHundepool** [comment]
We have added a fourth parameter to the TauArgus commandline. 
This parameter is the batch data directory. If no directory information is added to the name of the output file 
in <WRITETABLE> param(4) is added to the file name.
For the input files a file name without diretpory information is first searched in the directory of the .arb file.
If it cannot be found there we will then try the param(4) directory.

The named parameters will come later. For the time being a "-" as a second or third parameter will be interpreted as ignore this parameter.
