### ISSUE TITLE
<CLEAR> command in batch does not work properly?

### ISSUE THREAD

**Issue by ppdewolf** [sdcTools/UserSupport#58]
**SDC tool used:** tau-argus
**Version used:** 4.1.4 
**Operating system used:** Windows

---

When trying to protect two tables from within one .arb file, using the `<CLEAR>` command in between, the second `<READMICRODATA>` command throws an error.

Note: the `ClearIssue.*` and `ClearIssue2.*` are exactly the same files. The same error is also  thrown when in the .arb file `ClearIssue.*` is used twice.

[File with MWE: ClearIssue.zip](https://github.com/sdcTools/UserSupport/files/1004626/ClearIssue.zip)

Error message:
![error](https://cloud.githubusercontent.com/assets/19729987/26109232/278eb1c6-3a4f-11e7-849d-8cd01718dc95.jpg)

Log info in progress window shows something strange as well:
![log](https://cloud.githubusercontent.com/assets/19729987/26109231/278d7c66-3a4f-11e7-9ef3-f4fdf0a86e7e.JPG)

**Comment by AncoHundepool** [comment]
Solved. I added a few more clear-commands when executing the <CLEAR> command.
This might be a solution for #36 too.
