### ISSUE TITLE
batch-mode: functionality to query current version

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#59]
**SDC tool used:** Tau-Argus
**Version used:**  4.1.5
**Operating system used:** Windows
---

it would be very useful, if it was possible to query the version of argus that is used when calling it with batch-mode.

**Comment by AncoHundepool** [comment]
A new option has been added to the batch-command
<VERSIONINFO>   filename

This will create a new output file, containing the version number of the GUI including the build number.
Similar as in <WRITETABLE> the batch output path will be prefixed if no directory information can be found.

**Comment by the-knife** [comment]
How to use that option in practice? Didn't find anything about it in the 4.1 manual.

**Comment by ppdewolf** [comment]
If you make a .arb file with the line 
`<VERSIONINFO> "foo.txt"`
it will write the version info to the file `foo.txt` as follows:
`TAU-ARGUS version: 4.1.13_BETA; build: 1`
