### ISSUE TITLE
Inconsistent documentation of request rule

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#61]
**SDC tool used:** tau-argus
**Version used:**  4.1.5
**Operating system used:** Windows
---

In the user manual of tau-argus the parametrization of the request rule is described on page 123 as:

`REQ: (Percent1, Percent2, SafetyMargin)`.

In the GUI, users need to set 4 values, which are then used in `REQ()`  in the `<SAFETYRULE>` statement in a batch-file in the following way:

`<SAFETYRULE> REQ(Ind-1, Ind-2, MinFreq, Safety range)`.  

On page 92, the implementation of the request-rule is described stating that the violation of an additional frequency rule is also checked (my guess is that this would be the parameters `MinFreq` and `Safety range`). It is (at least for me unclear) however, why it is possible to specify two percentage parameters (`Ind-1` and `Ind-2`) and how they are used. It would be great if this could be clarified.

**Comment by AncoHundepool** [comment]
You will get an answer next week.

**Comment by bernhard-da** [comment]
thx!

**Comment by AncoHundepool** [comment]
It is not really an inconsistency, but it is not really complete.
Our friends in the Foreign Trade department asked for two different thresholds.
They wanted to give the unsafe cells of the previous year an extra protection. 
Therefore you have two different codes for the request variable in the RDA file and two percentages when specifying the table.
If you are not interested in this, do not use the second code and the second percentage will not be used.

**Comment by bernhard-da** [comment]
@AncoHundepool thx for the clarification!

**Comment by AncoHundepool** [comment]
Nevertheless we should explain this a bit in the manual.
