### ISSUE TITLE
HRC files issue

### ISSUE THREAD

**Issue by julienlemasson** [sdcTools/UserSupport#62]
**SDC tool used:** Tau-argus
**Version used:**  3.5 and 4.1.5
**Operating system used:** 

Windows 7 64b
---
Hi I get some issues with a hierarchical variable. In fact the number of level is pretty high, and i wonder if there is a limit and if I reach it. 
I joins an extract of my microdata with the variable (an activity code variable), the hrc and rda files.

The issue happens when i try to do the hypercube suppression : 
- with 3.5 =>Tau-Argus just turn off 
- with 4.1.5 => I get the message "The hypercube could not be applied. See file PROTO002 4.1.5" =>
 "GHMITER run (2.2.22)

 started Fri Jun 09 09:30:02 2017

 Start with construction of the temp-file for table : EINGABE  UM Fri Jun 09 09:30:02 2017

 Read control-file for table : EINGABE                                  at Fri Jun 09 09:30:02 2017
 Number of keys       2540 larger as expected       1572
 Contact GHMITER user support
(Please change variable IW in subroutine HUNK0)"

My real data implies that I use hypercube, beaucause of the number of variable. 
Any idea of the nature of the issue and eventually a means of circumventing it ?

Thanx !
Julien form France.
[example JL.zip](https://github.com/sdcTools/UserSupport/files/1063287/example.JL.zip)

**Comment by AncoHundepool** [comment]
I think that you need the large data model for GHMiter. I will check this next week.

**Comment by julienlemasson** [comment]
I tried that too, but that makes same results for now. I tried also manual values, but I'm not sure of what value I should put on, so I tried 6000 and 25000000 but it does not works neither.

**Comment by ppdewolf** [comment]
There is indeed a limit to the number of levels in a hierarchy for the hypercube method. In the hypercube executable that is used, that limit is 10. However, in the GUI some file with information about the table is produced that only allows up to (and including) 8 levels. We will make this consistent to 10 max levels.

For now, be sure the stay below (or equal to) 8 levels.

**Comment by ppdewolf** [comment]
Fixed. Will be included in version 4.1.6 of tau-argus.

**Comment by julienlemasson** [comment]
Hi, 
thank you for the information, and good news for 4.1.6.
For my current datas, I will probably do the secondary secret on a second time on Sas for some of the specials aggregates (that are responsibles of too many lvls).

**Comment by ppdewolf** [comment]
You could try replacing `TauArgusJava.dll` in your ARGUS-directory with [this test-release](https://github.com/sdcTools/libtauargus/releases/download/1.0.6.0/TauArgusJava.dll). Not fully tested yet, though. But will probably work.
