### ISSUE TITLE
CheckTauArgus: Spaces in path

### ISSUE THREAD

**Issue by junoslukan** [sdcTools/UserSupport#63]
**SDC tool used:** checkTauArgus
**Version used:** 0.1.0 
**Operating system used:** Windows

---

Spaces in the path to the Tau Argus executable present a problem for the function `checkArgus()`. 

When using `checkArgus("E:\\Program Files (x86)\\TauArgus4.1.5\\TauArgus.exe")` or `checkArgus("E:/Program Files (x86)/TauArgus4.1.5/TauArgus.exe")` I get the following error:

` Error in system(cmd, intern = TRUE, ignore.stdout = TRUE, ignore.stderr = FALSE) : 
  'E:/Program' not found `.

Since `Program Files (x86)` is a common path for programmes to be installed in Windows, it would be convenient if there is a way to resolve this.

**Comment by bernhard-da** [comment]
hi @junoslukan,

thx for reporting. i was able to reproduce the issue which will be fixed in the next sdcTable release.

**Comment by g3o2** [comment]
As temporary workaround, replacing `E:\\Program Files (x86)\\`by `%ProgramFiles(x86)%\\` should solve the problem. See this [wiki article](https://en.wikipedia.org/wiki/Environment_variable#Default_values) for further information on environment variables.

**Comment by ppdewolf** [comment]
Work around does not help in my case (using sdcTable version 0.22.6):
`checkArgus("C:\\Users\\pwof\\Documents\\Argus\ Open\ Source\ Releases\\TauArgus4.1.6\\TauArgus.exe",what=c("Batch"))`

**Comment by bernhard-da** [comment]
hi, I need to check with the latest tau-Argus version before I can update sdcTable and also checkTauArgus to fix this issue which I hopefully can do later this week.

**Comment by bernhard-da** [comment]
fixed.
