### ISSUE TITLE
Path name to Cplex license file for Audit routine

### ISSUE THREAD

**Issue by ppdewolf** [sdcTools/UserSupport#64]
**SDC tool used:** tau-argus
**Version used:**  4.1.5
**Operating system used:** Windows

---

Specifying the Cplex license file in the Options menu with only the file-name (e.g., `access.ilm`) works for Suppress methods (if that file resides in the same directory as tau-argus). For the Audit method it seems that a full path is needed. Can you make that more flexible for the Audit routine?

**Comment by AncoHundepool** [comment]
Not a big thing. It will be solved. 
A better check will be included to locate the .ilm file even if  the path is not specified.

**Comment by AncoHundepool** [comment]
If the licence file does not contain path information we will add the application path.
If the CPlex licence file could not be found, an exception/error will be raised.
