### ISSUE TITLE
URI has an authority component error

### ISSUE THREAD

**Issue by ksak3** [sdcTools/UserSupport#68]
**SDC tool used:** tau Argus
**Version used: 4.1.6 and 4.1.3**  
**Operating system used:** Windows 7

Hi I have moved to a new computer system and installed tau argus 4.1.6 bundled with JRE7 as well as 4.1.3.  I have several batch files that run linked tables that run perfectly on 4.1.3 on my old computer (they are on a network so I am accessing the exact same files) but when I try to run them on the new one (whether from batch or GUI) I get an error: 

URI has an authority component 
error running the cover table

The internet tells me this may have something to do with Java but does not provide me with a fix.  I can run non-linked tables just fine. 

Thanks for any help, Saki

**Comment by ppdewolf** [comment]
Not sure, but it might have something to do with the file-paths in your batch-files. Could you give an example? Are you using mapped disk-names (like F:\test.arb where F: is a mapped \\cbs.nl\work\) or are you using UNC-paths (like \\cbs.nl\work\test.arb)?

**Comment by ksak3** [comment]
I am using UNC paths. The temp directory is the default location on the C drive.  Tau Argus seems to be able to read the paths of the log, csv, rda, and hst files, and is creating temp rda, tab, arb and htm files. Also it runs fine if the tables aren't linked.  I get the same error with 4.1.3.

**Comment by ksak3** [comment]
I moved tau Argus itself and that fixed the problem. Thanks!

**Comment by ppdewolf** [comment]
Could you say a bit more about "moved tau Argus itself"? From where to where? 

Could be of help to other users.

**Comment by ksak3** [comment]
This is my first time using a VDI system and I did not realize that the 'Desktop' I uploaded the software to was not on C drive but a UNC location. I moved it to C drive and it worked.
