### ISSUE TITLE
Option Zero unsafe doesn't work properly

### ISSUE THREAD

**Issue by mancag** [sdcTools/UserSupport#69]
**SDC tool used:** tau-argus  
**Version used:**  3.5.0, 4.1.4, 4.1.6
**Operating system used:** Windows

---

Dear all,

Option Zero unsafe doesn't work properly in Tau-Argus versions 3.5.0, 4.1.4, 4.1.6. If recoding for explanatory variables is used, then some zero cells might not be primary sensitive. (But if there is no recoding, all zero cells are primary sensitive.)

Simple example:
1. Open tau_testW.asc with tau_testW.rda.
2. Specify table IndustryCode x Size | Var2 with Zero unsafe (range = 10.0)  and no other sensitivity rules.
3. Check in table summary that there are 3 unsafe cells due to "zero cell" rule.
4. Recode IndustryCode to Maximum level 2.
5. The zeros in cells IndustryCode = 157..., Size = 2 are no longer recognized as unsafe.

Best,
Manca

**Comment by ppdewolf** [comment]
Additional info: same happens when using recode on a non-hierarchical variable (Size x Region and recode Size with `1: 2-4`)

**Comment by ppdewolf** [comment]
Will be solved in next release (version 4.1.7).
