### ISSUE TITLE
2016006 2016-04-04 (Destatis)

### ISSUE THREAD

**Issue by rvdlaar8** [sdcTools/UserSupport#7]
Version used: 4.1.3
## Windows

Scaled costs (lambda=0.4) lijkt niet altijd te werken zoals verwacht.
Als je de costs scaled, komt er bij modular en optimal iets anders uit (één dimensionaal voorbeeld). 
Wellicht: optimal = eerst schalen naar 20000 dan integer weight, modular = eerst integer weight dan schalen naar 20000?

**Comment by ppdewolf** [comment]
This is related to issue #34

**Comment by ppdewolf** [comment]
Consistent behaviour for Optimal and Modular implemented (scaling of costs will be done irrespective of need, i.e., also when total is already smaller than MAXWEIGHT).
Solution will be included in next release.
