### ISSUE TITLE
Calculation of combinations is wrong (incorrect threshold?)

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#70]
**SDC tool used:** mu-argus
**Version used:**  5.1.1 (build 1)
**Operating system used:** Windows
---

When implementing the combinations feature of mu-argus in sdcMicro, I was realizing some strange things which I consider to be a bug.

To reproduce: use the asc and rda-file from [**this zip-file**](https://github.com/sdcTools/UserSupport/files/1327276/debug_combs.zip)

Then, perform the following steps in mu-argus

- `Specify` -> `Combinations`
- Select `Automatic specification of tables`
- In popup-window select `Make all tables up to combination`, enter value `2` and press `Ok`
- In the next popup-window enter `5` (default value) for `Threshold dimension 1` and press `Ok`
- Enter `10` (default value) for `Threshold dimension 2` and press `Ok`
- Press `Calculate tables`
- Go to `Modify` -> `Show table collection`. 
![screen4](https://user-images.githubusercontent.com/5228437/30782484-5b2cdb70-a133-11e7-9e99-9d445a0edd17.png)
In the result we see we have two combinations of variables with unsafe cells (`urbrur` x `roof` with 2 unsafe cells and `urbrur` x `walls` with 1 unsafe cell). Note that no univariate variable contains unsafe cells with threshold `5`.

Then go back to 

- `Specify` -> `Combinations`
- Select `Automatic specification of tables` and confirm to delete the current set of tables
- In popup-window select `Make all tables up to combination`, enter value `3` and press `Ok`
- In the next popup-window enter `5` (default value) for `Threshold dimension 1` and press `Ok`
- Enter `10` (default value) for `Threshold dimension 2` and press `Ok`
- Enter `20` (default value) for `Threshold dimension 3` and press `Ok`
- Press `Calculate tables`
- Go to `Modify` -> `Show table collection`. In the result 
![screen3](https://user-images.githubusercontent.com/5228437/30782454-f889fbc4-a132-11e7-9787-77f9fbb9b9ea.png)
we see we have 5 combinations of variables with unsafe cells. However we have now also a combination just consisting of variable `roof` with `2` unsafe cells, which is a bug. Also, the number of unsafe cells in the combination `urbrur` x `roof` is different in the two outputs. I think, incorrect thresholds are used (they are correctly shown in `Specify` -> `Combinations` though.

**Comment by ppdewolf** [comment]
What seems to happen is that the threshold of dim 3 is used all the way: cells in marginals of a 3-dim combination/table seem get the same threshold as interior cells. This is suggested by looking at the unsafe combinations of `roof`: 
![afbeelding](https://user-images.githubusercontent.com/19729987/31385062-f57d5ed0-adc1-11e7-863f-68a15a1155a5.png)
This should obviously not be te case (why specify different tresholds if you don't use them 😉). We'll look into this.

**Comment by ppdewolf** [comment]
What's done at the moment is that the largest threshold for a certain cell is used. I.e., roof appears in a 1dim combination with threshold 5, 2dim table with threshold 10, 3dim table with threshold 20. Then threshold 20 is used.

However, it's more intuitive to have lower thresholds in higher dimensional combination compared to a lower dimensional combination.

**Comment by ppdewolf** [comment]
Like mentioned in the previous comment, the most restrictive threshold for a cell is used. 
Moreover, it is more logical to have lower thresholds in higher dimensional combinations compared to lower dimensional combinations.
Concerning the "default" thresholds: mu-argus remembers the thresholds used in a previous run. The "real" default when starting mu-argus for the first time is a threshold 1 for all situations.

I close this issue now, since the behaviour may be a bit surprising at first sight, but is actually logical.
