### ISSUE TITLE
How are combinations using identification level calculated?

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#71]
**SDC tool used:** mu-argus
**Version used: 5.1.1b1**  
**Operating system used:** windows
---

using [**these testdata**](https://github.com/sdcTools/UserSupport/files/1339746/testinput_muargus.zip), I am having difficulties to understand, why some combinations are computed using the combinations functionality. the manual (p. 71) states:

> ... by using the identification levels of all variables, provided that they have been specified by the user. In this case μ-ARGUS generates all tables that can be obtained when variables from different levels of identification are chosen. In this case a single threshold should be specified. This option is the Dutch approach for Micro data files Under Contract (MUC).

to reproduce: after loading the microdata and the metadatafile, I performed the following steps:
`Specify` -> `Combinations` -> `Automatic specification of tables` -> `Use identification level`. Then set threshold to `10`. Afterwards, in the preview-window on the right hand side, the following 4-dimensional combinations are listed:

![muargus_screen1](https://user-images.githubusercontent.com/5228437/30954248-bab1d1fa-a42f-11e7-8615-22e42e28fe98.PNG)

There are some combinations shown (e.g. `urbrur` (1) x `roof` (1) x `walls` (2) x `water` (3)) in which some variables have the same identification level (in parenthesis) are shown (unexpected) while other combinations (e.g. `walls` (2) x `water` (3) x `electcon` (3) x `sex` (5)) that also have some common identification levels are not shown (expected).

So my question is why there are some combinations with common id-levels shown while others are not.

**Comment by ppdewolf** [comment]
Not clearly stated in the manual, is that the identification levels are considered to be "nested", in the sense that a level `i` variable is automatically a level `i+1` variable. Additionally, only combinations of levels `1 x 2 x 3 x ...` are chosen. This is "Dutch approach". 

By the way, in your situation (with levels 1, 2, 3 and 5, i.e., no level 4) you would have combinations of variables in levels `1 x 2 x 3 x 4 x 5`. Since no variabel has level 4, you end up with `1 x 2 x 3 x 5`.

**Comment by bernhard-da** [comment]
hi, thx for the clarification. but why is `walls` (2) x `water` (3) x `electcon` (3) x `sex` (5) missing then?

**Comment by ppdewolf** [comment]
Because that combination has no level 1 variable.

In case you have only levels 2, 3 and 4, it will also look for `1 x 2 x 3 x 4`, but without any level 1 variable, it will effectively only create `2 x 3 x 4`.

**Comment by bernhard-da** [comment]
hi @ppdewolf, thx for trying to explain to me. I am still not getting the same results and have difficulties to understand the logic.

e.g.
- `walls` (2) x `water` (3) x `electcon` (3) is included in the mu-argus output, even though no "variable with idlevel 1 (the minimum) is part of this combination and two variables have the same idlevel
- `urbrur` (1) x `water` (3) x `electcon` (3) x `sex` (5) is not included, even though this combination includes a variable with idlevel 1 and it has also two contributing variables with the same level.

I think for the moment I'll implement this approach in sdcMicro by computing all 1:n-dimensional combinations of the key variables not considering these edge-cases which will result in slightly more tables to check and call it the "austrian approach" :)

**Comment by ppdewolf** [comment]
Perhaps this picture helps?
[Schema.pdf](https://github.com/sdcTools/UserSupport/files/1445510/Schema.pdf)
