### ISSUE TITLE
Xpress solver license error

### ISSUE THREAD

**Issue by ksak3** [sdcTools/UserSupport#74]
**SDC tool used:** tau-argus 
**Version used:**  4.1.6
**Operating system used:** Windows

---

Has anyone recently installed the tau-Argus Xpress license? Tau Argus can find the license but the Xpress log file says that the OEM number is not correct.  FICO does not seem able to fix it.

**Comment by ppdewolf** [comment]
This is strange. New users of tau-argus with Xpress should no longer get an OEM licence. TO be able to get a discount, they will have to sign a contract that states they will use the Xpress licence for tau-argus only. FICO should know about this. You could refer to Oliver Bastert (from FICO) about this. He was our contact at FICO about this.
