### ISSUE TITLE
Cannot produce working rda file

### ISSUE THREAD

**Issue by bachfab** [sdcTools/UserSupport#76]
**SDC tool used:** (mu-argus)  
**Version used:**  5.1.1 build 1
**Operating system used:** (Windows)

When I try to re-use a previously working rda file (no changes made to data nor rda metadata), I now get an error message when clicking "Calculate tables" (error1.PNG attached). I can reproduce this using attached dummy.csv with meta.rda. Now when I try instead to re-generate the rda information ("Free with meta" -> "Generate" and saving as meta_new.rda also attached), I get another error message when clicking "Generate tables" (error2.PNG attached). Comparing meta.rda with meta_new.rda, I see that indeed the only difference is the missing separator info in line 1 of meta_new.rda (known issue #16 ). When I add this line by hand and try to calculate tables using edited meta_new.rda, error1.PNG is reproduced. In any case, I am not currently able to produce any tables from dummy.csv, neither re-using (previously working) rda info, nor re-generating it anew using the built-in function.

[attachments.zip](https://github.com/sdcTools/UserSupport/files/1440707/attachments.zip)

---

**Comment by ppdewolf** [comment]
If `Free with meta` is used as input, the first lines of the `.rda`-file should be
`<SEPARATOR> ","`
`<NAMESINFRONT>`
The second line specifies that the names of the variables are on the first line of the data-file. (See manual, page 85).
I'll add this to issue #16 to be added as something that is not currently written to the generated metafile.

**Comment by ppdewolf** [comment]
Merged with issue #16.
