### ISSUE TITLE
Code for the Total

### ISSUE THREAD

**Issue by borisfrenkie** [sdcTools/UserSupport#77]
*Please specify*  
**SDC tool used:** tau-Argus 
**Version used:**  4.1.6 b2
**Operating system used:** Windows

---
Hi,

when I save protected table, the name of the total that I specified in the metadata file is rewritten by the "Total" code. Could it be possible to preserve the original code for the total?

**Comment by ppdewolf** [comment]
Could you be a bit more specific? Are you using microdata or tabular data as input? Or does it happen in both situations? Can you give an example to reproduce the behaviour?

**Comment by AncoHundepool** [comment]
In the few examples I tried the protected table gets the total code as specified in the RDA. So please help us.

**Comment by borisfrenkie** [comment]
I use mainly tabular data as input, find attached a simple artificial table to reproduce the question. In the zip file you can find the data, hierarchies, metadata and output I got (code value). 

Maybe I'm just missing something. 

[example.zip](https://github.com/sdcTools/UserSupport/files/1474990/example.zip)

**Comment by ppdewolf** [comment]
It seems to happen only with tabular data input. In displaying the table it is OK, but only when writing to file it is replaced.

**Comment by ppdewolf** [comment]
Perhaps related to issue #75?

**Comment by ppdewolf** [comment]
Will be solved in version 4.1.7.

**Comment by APoStat** [comment]
(Only?) intermediate format has real total codes, and that's why I use it. But format has other difficulties... #36
