### ISSUE TITLE
Combination of distance function and protected cells not working

### ISSUE THREAD

**Issue by sven-grunwald** [sdcTools/UserSupport#79]
*Please specify*  
**SDC tool used:** tau-argus
**Version used:**  4.1.6 build 2
**Operating system used:** Windows

---

In version 4.1.6 build 2 the combination of distance function and protected cells is not working properly (for comparisson in 3.5.0 build 27 everything was fine). In this case, as soon as you have a primary supressed cell in a subtable, the whole subtable is suppressed (i.e. tau-argus doesn't find a solution).

Attached you'll find three arb-files with a little instance:
1) "with_protected"
2) "with_distance"
3) "with_both"

All arb files protect the same table, but while the first one deals with protected cells and without distance function, the second one the other way round (without protected cells and with distance funtion), the third one uses both options. The first two work properly, but the combination doesn't.  

[bug_protected_distance.zip](https://github.com/sdcTools/UserSupport/files/1508985/bug_protected_distance.zip)

**Comment by ppdewolf** [comment]
Will be solved in version 4.1.7 of tauargus.
Was an unexpected side-effect of solving issue #7.

**Comment by ppdewolf** [comment]
You may try to use the tauhitas.dll (version 4.3.4) in the release section of the tauhitas repository. Copy that file over the one in your tauargus directory. Cannot guarantee that it will work that way, but you can try.
