### ISSUE TITLE
write.table arguments not passed correctly to writeSafeFile

### ISSUE THREAD

**Issue by bachfab** [sdcTools/UserSupport#80]
*Please specify*  
**SDC tool used:** sdcMicro
**Version used:**  5.0.5
**Operating system used:** Windows

---
The documentation for the sdcMicro function `writeSafeFile` states

> ... | optional arguments used for write.table if argument format equals csv

However, additional standard arguments to `write.table` don't seem to be effective (at least some of them). E.g. when calling

`writeSafeFile(obj=sdcObj, format="csv", randomizeRecords="no", col.names=TRUE, sep=",", dec=".", quote=FALSE, na="", row.names=FALSE, fileOut=...)`

I still get output lines that look like

`"1",NA,NA,NA,"2",...`

where the initial "1" is the line number added automatically. So it seems like at least the options `quote=FALSE`, `na=""`, `row.names=FALSE` have no effect.

(I checked correct syntax and desired behaviour with a dummy call to `write.table` with these options.)

**Comment by bernhard-da** [comment]
hi @bachfab, thx for reporting this. i just fixed the issue in https://github.com/sdcTools/sdcMicro/commit/da7fff1c1e31be75c0ba9ba25888273cfd4610c4 in the next-branch and the fix will be included in the next version of sdcMicro.
