### ISSUE TITLE
RDA file not produced by batch with intermediate format output

### ISSUE THREAD

**Issue by julienlemasson** [sdcTools/UserSupport#82]
SDC tool used : tau-argus
Version used: 4.1.6 
Operating system used: (Windows (aus))

Hi, 
I execute a batch file from SAS who contains these lines :
(I don't let the "<" in the begining of the line, it seems to make trouble on edition on the github, but it is on the original batch)
*******************************
OPENMICRODATA>  "(...)\microdata.asc"
OPENMETADATA>   "(...)\metadata.rda"
SPECIFYTABLE>   "SEXE""CE""CS1""TRAGE_12"|"SALAIRE"|""|""
SAFETYRULE>    NK(1,85)|NK(0,0)|FREQ(3,10)|MAN(10)
SPECIFYTABLE>   "SEXE""CE""CS1""A88"|"SALAIRE"|""|""
SAFETYRULE>     NK(1,85)|NK(0,0)|FREQ(3,10)|MAN(10)
SPECIFYTABLE>   "SEXE""CE""NAF"|"SALAIRE"|""|""
SAFETYRULE>     NK(1,85)|NK(0,0)|FREQ(3,10)|MAN(10)
SPECIFYTABLE>   "SEXE""CE""TREFF_12"|"SALAIRE"|""|""
SAFETYRULE>     NK(1,85)|NK(0,0)|FREQ(3,10)|MAN(10)
SPECIFYTABLE>   "SEXE""CE""A38"|"SALAIRE"|""|""
SAFETYRULE>     NK(1,85)|NK(0,0)|FREQ(3,10)|MAN(10)
SPECIFYTABLE>   "SEXE""CE""CS""DEP"|"SALAIRE"|""|""
SAFETYRULE>     NK(1,85)|NK(0,0)|FREQ(3,10)|MAN(10)
SPECIFYTABLE>   "SEXE""CE""A17""DEP"|"SALAIRE"|""|""
SAFETYRULE>     NK(1,85)|NK(0,0)|FREQ(3,10)|MAN(10)
SPECIFYTABLE>   "SEXE""CE""TREFF_4""REG"|"SALAIRE"|""|""
SAFETYRULE>     NK(1,85)|NK(0,0)|FREQ(3,10)|MAN(10)
SPECIFYTABLE>   "SEXE""CE""TRAGE_3""CS1""REG"|"SALAIRE"|""|""
SAFETYRULE>     NK(1,85)|NK(0,0)|FREQ(3,10)|MAN(10)
READMICRODATA>
WRITETABLE>     (1,5,,"(...)\sexe_ce_cs1_trage12_salaire.tab")
WRITETABLE>     (2,5,,"(...)\sexe_ce_cs1_a88_salaire.tab")
WRITETABLE>     (3,5,,"(...)\sexe_ce_naf_salaire.tab")
WRITETABLE>     (4,5,,"(...)\sexe_ce_treff12_salaire.tab")
WRITETABLE>     (5,5,,"(...)\sexe_ce_a38_salaire.tab")
WRITETABLE>     (6,5,,"(...)\sexe_ce_cs_dep_salaire.tab")
WRITETABLE>     (7,5,,"(...)\sexe_ce_a17_dep_salaire.tab")
WRITETABLE>     (8,5,,"(...)\sexe_ce_treff4_reg_salaire.
WRITETABLE>     (9,5,,"(...)\sexe_ce_trage3_cs1_reg_salaire.tab")
*******************************
In output, some of the rda files (that should come with the .tab produced) are missing : the "number" 2,6,7 and 9). 

Then, i tried to produce the tables one by one. So i produce a batch file and execute them from SAS : here is the last one : 
*******************************
OPENMICRODATA>  "(...)\microdata.asc"
OPENMETADATA>   "(...)\metadata.rda"
SPECIFYTABLE>   "SEXE""CE""TRAGE_3""CS1""REG"|"SALAIRE"|""|""
SAFETYRULE>     NK(1,85)|NK(0,0)|FREQ(3,10)|MAN(10)
READMICRODATA>
WRITETABLE>     (1,5,,"(...)\sexe_ce_trage3_cs1_reg_salaire.tab")
*******************************
This time in output the 1,2,3,6,7 and 9 's rda files are missing. 

I tried to execute the batch file by double clicking on it and choose TA as the program to read it. Same result. 

When I first open TA and then go file>open batch process... and launch it from TA, I get the rda files in output...

When I redo all the tests with 3.5 TA version, I always got the RDA in output (plus some copies of hrc).

So I get a solution for my issue (using 3.5) but that is kinda weird and I have no idea what's wrong here.

TY and happy new year !

**Comment by ppdewolf** [comment]
This seems to be related to issue #36 . Probably solved in version 4.1.7.
I've just launched a pre-release of version 4.1.7 to be tested: [Pre release 4.1.7](https://github.com/sdcTools/tauargus/releases/tag/4.1.7) 
So, if you feel lucky, you can try testing 😃

**Comment by julienlemasson** [comment]
I tryed this new version and that works well. I get all my rda's files.

Thanx a lot !

**Comment by ppdewolf** [comment]
Good to know!
