### ISSUE TITLE
inconsistent behaviour batchfile vs direct input

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/UserSupport#86]
**SDC tool used:** tau-argus, sdcTable
**Version used:**  4.1.6 (tau-argus) and 0.22.8 (sdcTable)
**Operating system used:** windows
---

hi @ppdewolf , i got [**this issue**](https://github.com/bernhard-da/sdcTable/issues/37) which I can reproduce. i can load the microdata-file (asc) together with the metadata-file (rda) generated using `createArgusInput()` without issue directly into tau-argus (`File` -> `Open Microdata`) but can't upload the generated batch-File. The logfile stops at `<READMICRODATA>`.

is argus doing something differently wheater you upload the microdata-file or the batch-file? The inputs I've used including the log-file are attached.

[**sdcTable_tau_issue.zip**](https://github.com/sdcTools/UserSupport/files/1720253/sdcTable_tau_issue.zip)

**Comment by ppdewolf** [comment]
When fixing the use of `<FREQ>` in `<SPECIFYTABLE>` in batch with tabular input (see comments issue #65), the use of `<FREQ>` in `<SPECIFYTABLE>` in batch with microdata input got broken. This will be fixed in next release (version 4.1.7 build 4).

**Comment by bernhard-da** [comment]
thx for answering @ppdewolf !

**Comment by ppdewolf** [comment]
Just updated the pre-release for testing to build 4
