### ISSUE TITLE
Optimal dos not work with 4.1.7 version of TA

### ISSUE THREAD

**Issue by julienlemasson** [sdcTools/UserSupport#87]
*Please specify*  
**SDC tool used:** tau-argus
**Version used:**  4.1.7b4bundledJRE7 
**Operating system used:** (Windows
---
I tried few days ago to use Optimal solver with the 4.1.7b4bundledJRE7, with a batch file, and it did not work.
A windows appears : 
"Cplex licence files : V:\....Tau-Argus 4.1.7\access.ilm could not be found"
 I cheked that the option free solver was checked. I also tried in manual, and it did not work neither.
When I tried with the 4.1.6 version the same batch, it worked.

So no pb for me, since 4.1.6 work, but I don't know if I did something wrong or if the 4.1.7 has a issue.

Julien

**Comment by ppdewolf** [comment]
This is similar to issue #85. Apparently we didn't change it for the Optimal procedure.
The same workaround should hold though: just put an empty file `foo.ilm` somewhere and select that as licence file for Cplex in the `Options` dialog. Press `OK`. Go back to `Options` and select `Free Solver`. Optimal now will probably run with Free Solver.

**Comment by ppdewolf** [comment]
Will be fixed in next release (4.1.8).

**Comment by julienlemasson** [comment]
Ok thx for the tips!
