### ISSUE TITLE
Error with modular method and three linked tables

### ISSUE THREAD

**Issue by jj585** [sdcTools/UserSupport#92]
**SDC tool used:** tau-argus  
**Version used:** 4.1.7b4 
**Operating system used:** Windows 10 64bit

I am trying to protect three linked tables with modular method, but I receive an error in the output.

![error](https://user-images.githubusercontent.com/24804698/41526301-7cb8d880-72ec-11e8-9f2e-3e38fecfcaf7.png)
![modular](https://user-images.githubusercontent.com/24804698/41526313-86e4d728-72ec-11e8-9bb5-36c30a53e357.png)
[HiTaS.log](https://github.com/sdcTools/UserSupport/files/2110563/HiTaS.log)
[logbook.txt](https://github.com/sdcTools/UserSupport/files/2110564/logbook.txt)
[data.zip](https://github.com/sdcTools/UserSupport/files/2110565/data.zip)

**Comment by AncoHundepool** [comment]
Please what are you trying to do. In your example you specify exactly three identical tables. Nace1, nace2 and nace 3 are identical????

**Comment by ppdewolf** [comment]
It looks like you are trying to use three different _versions_ of NACE classification. The way you specify it, tau-argus thinks there are three different _variables_: nace1, nace2 and nace3. This results in a 5 dimensional cover table. See the tau-argus manual for which tables are allowed (pp. 98, manual version 4.1):

> When protecting a set of linked tables the restriction is that all tables are a sub-set of a theoretical cover table. The cover table is formed by building a table spanned by all explanatory variable from the individual tables and using the longest code list for each dimension. The dimensions are decided by looking for different names of explanatory variables. 

> As long as the cover table does not have more than 4 dimensions the linked tables approach is possible. 

> In the current implementation there is one restriction. For each of the spanning variables in the cover table the codelist and the hierarchy should be present in one of the linked tables. For all other tables the codelists and the hierarchy should be a subset of this cover hierarchy. And of course the set of linked tables should be consistent. The cells that are logical the same should have exactly the same value and status. If not the protection of the cover table will fail.

Also see pp. 23 of the manual for a more theoretical explanation.

**Comment by jj585** [comment]
I am trying to protect tables for Labour cost survey 2016 and I need to protect several magnitude tables where dimension variables are "size by enterprise" and "economic activity". Response variables are "number of employees", "hours actually worked", "paid hours", "labour costs" and "information on units" (5 tables in total).

The problem is with dimension "economic activity" as I can't define hierarchy properly in top-down approach for this dimension. Groups or subtotals/totals needed are not mutually exclusive or disjoint (see section 3.4.2 on page 22 in document "LCS2016 implementing arrangments - FINAL.pdf". It can be seen also when trying to construct a binary tree that it is not possible to include all subtotals needed in one binary tree. For example in the 1st tree (see nace1_tree1.pdf), there is no groups XGSO, XG_S and XO_S included which I include in the 2nd and 3rd trees.

Therefore I introduced 3 equal columns in micro-data that represent economic activity with different names (nace1, nace2 and nace3 respectively) and defined three separate hierarchies for each and tried to protect them as linked tables.

Is my approach actually correct in the first place?
Is there any better solution to this problem when it is not possible to define a hierarchy for a dimensional variable in one file other than protect via linked table approach?

[LCS2016 implementing arrangments - FINAL.pdf](https://github.com/sdcTools/UserSupport/files/2114139/LCS2016.implementing.arrangments.-.FINAL.pdf)
[nace1_tree1.pdf](https://github.com/sdcTools/UserSupport/files/2114141/nace1_tree1.pdf)
[nace2_tree2.pdf](https://github.com/sdcTools/UserSupport/files/2114142/nace2_tree2.pdf)
[nace3_tree3.pdf](https://github.com/sdcTools/UserSupport/files/2114143/nace3_tree3.pdf)
