### ISSUE TITLE
get TA number version

### ISSUE THREAD

**Issue by the-knife** [sdcTools/UserSupport#94]
**SDC tool used:** tau-argus
**Version used:**  3.* and 4.*
**Operating system used:** Windows

---

Hello,
(this is not an issue strictly speaking)
I just would like to know if there is a  way to get the number version of TauArgus, given the directory where **tauargus.exe** is.
My first idea is parsing _taunews.html_, but it feels a bit clumsy.

Pierre-Yves

**Comment by the-knife** [comment]
Thanks Peter-Paul (and sorry for not having carefully checked the recent issues).
I have one more question that I will ask in the other thread.

To answer your question about the utility, I'm writing a small wrapper in R to call TA in batch mode. I want to get the TA number for user information, before he starts anything.

**Comment by ppdewolf** [comment]
Note that the [sdcTable package](https://github.com/sdcTools/sdcTable) includes an R-wrapper to call TA in batch mode. You could get inspired by that code :wink:

**Comment by the-knife** [comment]
I did see that. ;-)
As my wrapper is quite simple (only a few TA options), I made the choice not to "depend" on that package.  I may reconsider that choice at some point.

**Comment by ppdewolf** [comment]
Perhaps you could take a look into the code and see how TA is wrapped, e.g. making use of calling the version-info facility in batch.

**Comment by ppdewolf** [comment]
If you make a `versioninfo.arb` file with the line 
`<VERSIONINFO> "foo.txt"`
it will write the version info to the file `foo.txt` as follows:
`TAU-ARGUS version: 4.1.13_BETA; build: 1`
You can then use it e.g. commandline with
`tauargus.exe versioninfo.arb`
