### ISSUE TITLE
Incorrect column header in saved tables with status

### ISSUE THREAD

**Issue by the-knife** [sdcTools/UserSupport#97]
**SDC tool used:** tau-argus
**Version used:**  4.1.7b4
**Operating system used:** Windows

---

When saving a **frequency** table in csv-pivot-table (2) or code-value (3)  with **variables names** and **status**, an unwanted comma is written in the header line :

```
"V2","V3","Freq",,"Status"
"Total","Total",8,1
"Total","S",2,5
...
```

The header has consequently one more field than the following lines. 
According to some tests I did, the problem only occurs when AS+ is specified (AS+FL+ for code-value) and response variable is &lt;freq&gt;.

**Comment by ppdewolf** [comment]
I noticed the same while working on the new "cell-key"  method. I've already fixed it in the cellkey branch of the tauargus repository.
